/********************************************************************
* FilterCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FilterCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFilterCint();
extern void G__cpp_setup_inheritanceFilterCint();
extern void G__cpp_setup_typetableFilterCint();
extern void G__cpp_setup_memvarFilterCint();
extern void G__cpp_setup_globalFilterCint();
extern void G__cpp_setup_memfuncFilterCint();
extern void G__cpp_setup_funcFilterCint();
extern void G__set_cpp_environmentFilterCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MFTriggerLvl1.h"
#include "MFTriggerLvl2.h"
#include "MFMagicCuts.h"
#include "MFGeomag.h"
#include "MFEvtNumber.h"
#include "MFDeltaT.h"
#include "MFParticleId.h"
#include "MFSoftwareTrigger.h"
#include "MFCosmics.h"
#include "MFEnergySlope.h"
#include "FilterIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FilterCintLN_TClass;
extern G__linked_taginfo G__FilterCintLN_TBuffer;
extern G__linked_taginfo G__FilterCintLN_TMemberInspector;
extern G__linked_taginfo G__FilterCintLN_TObject;
extern G__linked_taginfo G__FilterCintLN_TString;
extern G__linked_taginfo G__FilterCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__FilterCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FilterCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FilterCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FilterCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FilterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FilterCintLN_TEnv;
extern G__linked_taginfo G__FilterCintLN_TArrayD;
extern G__linked_taginfo G__FilterCintLN_MParContainer;
extern G__linked_taginfo G__FilterCintLN_MInputStreamID;
extern G__linked_taginfo G__FilterCintLN_MFilter;
extern G__linked_taginfo G__FilterCintLN_MParList;
extern G__linked_taginfo G__FilterCintLN_MTask;
extern G__linked_taginfo G__FilterCintLN_MMcTrig;
extern G__linked_taginfo G__FilterCintLN_MFTriggerLvl1;
extern G__linked_taginfo G__FilterCintLN_MFTriggerLvl1cLcLFilterType_t;
extern G__linked_taginfo G__FilterCintLN_MMcTriggerLvl2;
extern G__linked_taginfo G__FilterCintLN_MFTriggerLvl2;
extern G__linked_taginfo G__FilterCintLN_MFTriggerLvl2cLcLFilterType_t;
extern G__linked_taginfo G__FilterCintLN_MGeomCam;
extern G__linked_taginfo G__FilterCintLN_MHillas;
extern G__linked_taginfo G__FilterCintLN_MHillasSrc;
extern G__linked_taginfo G__FilterCintLN_MHillasExt;
extern G__linked_taginfo G__FilterCintLN_MNewImagePar;
extern G__linked_taginfo G__FilterCintLN_MParameterD;
extern G__linked_taginfo G__FilterCintLN_MHMatrix;
extern G__linked_taginfo G__FilterCintLN_MFMagicCuts;
extern G__linked_taginfo G__FilterCintLN_MFMagicCutscLcLThetaCut_t;
extern G__linked_taginfo G__FilterCintLN_MFMagicCutscLcLHadronnessCut_t;
extern G__linked_taginfo G__FilterCintLN_MFMagicCutscLcLdA;
extern G__linked_taginfo G__FilterCintLN_MMcEvt;
extern G__linked_taginfo G__FilterCintLN_MFGeomag;
extern G__linked_taginfo G__FilterCintLN_TExMap;
extern G__linked_taginfo G__FilterCintLN_MRawRunHeader;
extern G__linked_taginfo G__FilterCintLN_MRawEvtHeader;
extern G__linked_taginfo G__FilterCintLN_MFEvtNumber;
extern G__linked_taginfo G__FilterCintLN_TArrayI;
extern G__linked_taginfo G__FilterCintLN_MTime;
extern G__linked_taginfo G__FilterCintLN_MFDeltaT;
extern G__linked_taginfo G__FilterCintLN_MFParticleId;
extern G__linked_taginfo G__FilterCintLN_MFParticleIdcLcLFilterType_t;
extern G__linked_taginfo G__FilterCintLN_MSignalCam;
extern G__linked_taginfo G__FilterCintLN_MSignalPix;
extern G__linked_taginfo G__FilterCintLN_MArrivalTime;
extern G__linked_taginfo G__FilterCintLN_MFSoftwareTrigger;
extern G__linked_taginfo G__FilterCintLN_MFSoftwareTriggercLcLTriggerType_t;
extern G__linked_taginfo G__FilterCintLN_MFSoftwareTriggercLcLdA;
extern G__linked_taginfo G__FilterCintLN_MRawEvtData;
extern G__linked_taginfo G__FilterCintLN_MPedestalCam;
extern G__linked_taginfo G__FilterCintLN_MBadPixelsCam;
extern G__linked_taginfo G__FilterCintLN_MExtractedSignalCam;
extern G__linked_taginfo G__FilterCintLN_MFCosmics;
extern G__linked_taginfo G__FilterCintLN_MFEnergySlope;

/* STUB derived class for protected member access */
