/********************************************************************
* SqlCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SqlCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSqlCint();
extern void G__cpp_setup_inheritanceSqlCint();
extern void G__cpp_setup_typetableSqlCint();
extern void G__cpp_setup_memvarSqlCint();
extern void G__cpp_setup_globalSqlCint();
extern void G__cpp_setup_memfuncSqlCint();
extern void G__cpp_setup_funcSqlCint();
extern void G__set_cpp_environmentSqlCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MSQLServer.h"
#include "MSQLMagic.h"
#include "MTreeSQL.h"
#include "MBasketSQL.h"
#include "MBufferSQL.h"
#include "SqlIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SqlCintLN_TClass;
extern G__linked_taginfo G__SqlCintLN_TBuffer;
extern G__linked_taginfo G__SqlCintLN_TMemberInspector;
extern G__linked_taginfo G__SqlCintLN_TObject;
extern G__linked_taginfo G__SqlCintLN_TNamed;
extern G__linked_taginfo G__SqlCintLN_TCollection;
extern G__linked_taginfo G__SqlCintLN_TString;
extern G__linked_taginfo G__SqlCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SqlCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SqlCintLN_TList;
extern G__linked_taginfo G__SqlCintLN_TBrowser;
extern G__linked_taginfo G__SqlCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SqlCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SqlCintLN_TBufferFile;
extern G__linked_taginfo G__SqlCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SqlCintLN_TEnv;
extern G__linked_taginfo G__SqlCintLN_TArrayI;
extern G__linked_taginfo G__SqlCintLN_TSQLServer;
extern G__linked_taginfo G__SqlCintLN_TSQLResult;
extern G__linked_taginfo G__SqlCintLN_MTreeSQL;
extern G__linked_taginfo G__SqlCintLN_MSQLServer;
extern G__linked_taginfo G__SqlCintLN_MSQLServercLcLType_t;
extern G__linked_taginfo G__SqlCintLN_MSQLServercLcLdA;
extern G__linked_taginfo G__SqlCintLN_MSQLColumn;
extern G__linked_taginfo G__SqlCintLN_MSQLMagic;
extern G__linked_taginfo G__SqlCintLN_TAttFill;
extern G__linked_taginfo G__SqlCintLN_TTree;
extern G__linked_taginfo G__SqlCintLN_TBasket;
extern G__linked_taginfo G__SqlCintLN_TFile;
extern G__linked_taginfo G__SqlCintLN_TBranch;
extern G__linked_taginfo G__SqlCintLN_TAttLine;
extern G__linked_taginfo G__SqlCintLN_TAttMarker;
extern G__linked_taginfo G__SqlCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SqlCintLN_TSQLRow;
extern G__linked_taginfo G__SqlCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__SqlCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SqlCintLN_vectorlETSQLRowmUcOallocatorlETSQLRowmUgRsPgR;
extern G__linked_taginfo G__SqlCintLN_reverse_iteratorlEvectorlETSQLRowmUcOallocatorlETSQLRowmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SqlCintLN_TKey;
extern G__linked_taginfo G__SqlCintLN_MBasketSQL;
extern G__linked_taginfo G__SqlCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__SqlCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SqlCintLN_MBufferSQL;

/* STUB derived class for protected member access */
