/********************************************************************
* OptimCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error OptimCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableOptimCint();
extern void G__cpp_setup_inheritanceOptimCint();
extern void G__cpp_setup_typetableOptimCint();
extern void G__cpp_setup_memvarOptimCint();
extern void G__cpp_setup_globalOptimCint();
extern void G__cpp_setup_memfuncOptimCint();
extern void G__cpp_setup_funcOptimCint();
extern void G__set_cpp_environmentOptimCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MJOptimizeBase.h"
#include "MJOptimize.h"
#include "MJOptimizeCuts.h"
#include "MJOptimizeDisp.h"
#include "MJOptimizeEnergy.h"
#include "OptimIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__OptimCintLN_TClass;
extern G__linked_taginfo G__OptimCintLN_TBuffer;
extern G__linked_taginfo G__OptimCintLN_TMemberInspector;
extern G__linked_taginfo G__OptimCintLN_TObject;
extern G__linked_taginfo G__OptimCintLN_TString;
extern G__linked_taginfo G__OptimCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__OptimCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OptimCintLN_TList;
extern G__linked_taginfo G__OptimCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__OptimCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OptimCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__OptimCintLN_TArrayD;
extern G__linked_taginfo G__OptimCintLN_MParContainer;
extern G__linked_taginfo G__OptimCintLN_MEvtLoop;
extern G__linked_taginfo G__OptimCintLN_MJob;
extern G__linked_taginfo G__OptimCintLN_MTask;
extern G__linked_taginfo G__OptimCintLN_MFilter;
extern G__linked_taginfo G__OptimCintLN_MJOptimizeBase;
extern G__linked_taginfo G__OptimCintLN_TMinuit;
extern G__linked_taginfo G__OptimCintLN_MAlphaFitter;
extern G__linked_taginfo G__OptimCintLN_MParList;
extern G__linked_taginfo G__OptimCintLN_MFilterList;
extern G__linked_taginfo G__OptimCintLN_MHMatrix;
extern G__linked_taginfo G__OptimCintLN_MRead;
extern G__linked_taginfo G__OptimCintLN_MReadTree;
extern G__linked_taginfo G__OptimCintLN_MJOptimize;
extern G__linked_taginfo G__OptimCintLN_MJOptimizecLcLOptimizer_t;
extern G__linked_taginfo G__OptimCintLN_MHAlpha;
extern G__linked_taginfo G__OptimCintLN_MJOptimizeCuts;
extern G__linked_taginfo G__OptimCintLN_MJOptimizeDisp;
extern G__linked_taginfo G__OptimCintLN_MJOptimizeEnergy;

/* STUB derived class for protected member access */
