/********************************************************************
* CorsikaCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CorsikaCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCorsikaCint();
extern void G__cpp_setup_inheritanceCorsikaCint();
extern void G__cpp_setup_typetableCorsikaCint();
extern void G__cpp_setup_memvarCorsikaCint();
extern void G__cpp_setup_globalCorsikaCint();
extern void G__cpp_setup_memfuncCorsikaCint();
extern void G__cpp_setup_funcCorsikaCint();
extern void G__set_cpp_environmentCorsikaCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MCorsikaRunHeader.h"
#include "MCorsikaFormat.h"
#include "MCorsikaEvtHeader.h"
#include "MCorsikaRead.h"
#include "CorsikaIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CorsikaCintLN_TClass;
extern G__linked_taginfo G__CorsikaCintLN_TBuffer;
extern G__linked_taginfo G__CorsikaCintLN_TMemberInspector;
extern G__linked_taginfo G__CorsikaCintLN_TObject;
extern G__linked_taginfo G__CorsikaCintLN_TString;
extern G__linked_taginfo G__CorsikaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CorsikaCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CorsikaCintLN_TList;
extern G__linked_taginfo G__CorsikaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CorsikaCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CorsikaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CorsikaCintLN_fits;
extern G__linked_taginfo G__CorsikaCintLN_MParContainer;
extern G__linked_taginfo G__CorsikaCintLN_MTime;
extern G__linked_taginfo G__CorsikaCintLN_MCorsikaFormat;
extern G__linked_taginfo G__CorsikaCintLN_MCorsikaRunHeader;
extern G__linked_taginfo G__CorsikaCintLN_MCorsikaEvtHeader;
extern G__linked_taginfo G__CorsikaCintLN_MCorsikaRunHeadercLcLCerenkovFlag_t;
extern G__linked_taginfo G__CorsikaCintLN_TVector2;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CorsikaCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CorsikaCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__CorsikaCintLN_TVector3;
extern G__linked_taginfo G__CorsikaCintLN_MInputStreamID;
extern G__linked_taginfo G__CorsikaCintLN_MParList;
extern G__linked_taginfo G__CorsikaCintLN_MTask;
extern G__linked_taginfo G__CorsikaCintLN_MRead;
extern G__linked_taginfo G__CorsikaCintLN_TArrayF;
extern G__linked_taginfo G__CorsikaCintLN_MPhotonEvent;
extern G__linked_taginfo G__CorsikaCintLN_MCorsikaRead;
extern G__linked_taginfo G__CorsikaCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__CorsikaCintLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
