/********************************************************************
* FluxCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FluxCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFluxCint();
extern void G__cpp_setup_inheritanceFluxCint();
extern void G__cpp_setup_typetableFluxCint();
extern void G__cpp_setup_memvarFluxCint();
extern void G__cpp_setup_globalFluxCint();
extern void G__cpp_setup_memfuncFluxCint();
extern void G__cpp_setup_funcFluxCint();
extern void G__set_cpp_environmentFluxCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MAlphaFitter.h"
#include "MHAlpha.h"
#include "MHThetaSq.h"
#include "MHThetaSqN.h"
#include "MHPhi.h"
#include "MHDisp.h"
#include "MHFalseSource.h"
#include "MHEnergyEst.h"
#include "MHEffectiveOnTime.h"
#include "MHCollectionArea.h"
#include "MHThreshold.h"
#include "MMcSpectrumWeight.h"
#include "FluxIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FluxCintLN_TClass;
extern G__linked_taginfo G__FluxCintLN_TBuffer;
extern G__linked_taginfo G__FluxCintLN_TMemberInspector;
extern G__linked_taginfo G__FluxCintLN_TObject;
extern G__linked_taginfo G__FluxCintLN_TString;
extern G__linked_taginfo G__FluxCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FluxCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FluxCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FluxCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FluxCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FluxCintLN_TEnv;
extern G__linked_taginfo G__FluxCintLN_TArrayD;
extern G__linked_taginfo G__FluxCintLN_MParContainer;
extern G__linked_taginfo G__FluxCintLN_TF1;
extern G__linked_taginfo G__FluxCintLN_TH1D;
extern G__linked_taginfo G__FluxCintLN_TH3D;
extern G__linked_taginfo G__FluxCintLN_MAlphaFitter;
extern G__linked_taginfo G__FluxCintLN_MAlphaFittercLcLScaleMode_t;
extern G__linked_taginfo G__FluxCintLN_MAlphaFittercLcLStrategy_t;
extern G__linked_taginfo G__FluxCintLN_MAlphaFittercLcLSignalFunc_t;
extern G__linked_taginfo G__FluxCintLN_TH1;
extern G__linked_taginfo G__FluxCintLN_TH2;
extern G__linked_taginfo G__FluxCintLN_MBinning;
extern G__linked_taginfo G__FluxCintLN_MParList;
extern G__linked_taginfo G__FluxCintLN_TArrayI;
extern G__linked_taginfo G__FluxCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__FluxCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__FluxCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__FluxCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__FluxCintLN_TH2D;
extern G__linked_taginfo G__FluxCintLN_MH;
extern G__linked_taginfo G__FluxCintLN_MTime;
extern G__linked_taginfo G__FluxCintLN_MParameterD;
extern G__linked_taginfo G__FluxCintLN_MParameterI;
extern G__linked_taginfo G__FluxCintLN_MHillas;
extern G__linked_taginfo G__FluxCintLN_MHMatrix;
extern G__linked_taginfo G__FluxCintLN_MPointingPos;
extern G__linked_taginfo G__FluxCintLN_MHAlpha;
extern G__linked_taginfo G__FluxCintLN_MHThetaSq;
extern G__linked_taginfo G__FluxCintLN_TVector2;
extern G__linked_taginfo G__FluxCintLN_MGeomCam;
extern G__linked_taginfo G__FluxCintLN_MSrcPosCam;
extern G__linked_taginfo G__FluxCintLN_MHThetaSqN;
extern G__linked_taginfo G__FluxCintLN_MHPhi;
extern G__linked_taginfo G__FluxCintLN_MObservatory;
extern G__linked_taginfo G__FluxCintLN_MHFalseSource;
extern G__linked_taginfo G__FluxCintLN_MPointingDev;
extern G__linked_taginfo G__FluxCintLN_MHDisp;
extern G__linked_taginfo G__FluxCintLN_MMcEvt;
extern G__linked_taginfo G__FluxCintLN_MHEnergyEst;
extern G__linked_taginfo G__FluxCintLN_MParameterDerr;
extern G__linked_taginfo G__FluxCintLN_MHEffectiveOnTime;
extern G__linked_taginfo G__FluxCintLN_MMcRunHeader;
extern G__linked_taginfo G__FluxCintLN_MHCollectionArea;
extern G__linked_taginfo G__FluxCintLN_MHThreshold;
extern G__linked_taginfo G__FluxCintLN_MInputStreamID;
extern G__linked_taginfo G__FluxCintLN_MTask;
extern G__linked_taginfo G__FluxCintLN_MMcCorsikaRunHeader;
extern G__linked_taginfo G__FluxCintLN_MMcSpectrumWeight;

/* STUB derived class for protected member access */
