/********************************************************************
* PointingCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PointingCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePointingCint();
extern void G__cpp_setup_inheritancePointingCint();
extern void G__cpp_setup_typetablePointingCint();
extern void G__cpp_setup_memvarPointingCint();
extern void G__cpp_setup_globalPointingCint();
extern void G__cpp_setup_memfuncPointingCint();
extern void G__cpp_setup_funcPointingCint();
extern void G__set_cpp_environmentPointingCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MPointing.h"
#include "MPointingDev.h"
#include "MPointingDevCalc.h"
#include "MPointingPos.h"
#include "MPointingPosCalc.h"
#include "MPointingPosInterpolate.h"
#include "MHPointing.h"
#include "MHSrcPosCam.h"
#include "MSrcPosCam.h"
#include "MSrcPosCalc.h"
#include "MSrcPosRndm.h"
#include "MSrcPosCorrect.h"
#include "MSrcPosFromModel.h"
#include "PointingIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PointingCintLN_TClass;
extern G__linked_taginfo G__PointingCintLN_TBuffer;
extern G__linked_taginfo G__PointingCintLN_TMemberInspector;
extern G__linked_taginfo G__PointingCintLN_TObject;
extern G__linked_taginfo G__PointingCintLN_TString;
extern G__linked_taginfo G__PointingCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PointingCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PointingCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PointingCintLN_TClonesArray;
extern G__linked_taginfo G__PointingCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PointingCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PointingCintLN_TArrayD;
extern G__linked_taginfo G__PointingCintLN_TVector2;
extern G__linked_taginfo G__PointingCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PointingCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PointingCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__PointingCintLN_TVector3;
extern G__linked_taginfo G__PointingCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PointingCintLN_fits;
extern G__linked_taginfo G__PointingCintLN_TEnv;
extern G__linked_taginfo G__PointingCintLN_MParContainer;
extern G__linked_taginfo G__PointingCintLN_AltAz;
extern G__linked_taginfo G__PointingCintLN_ZdAz;
extern G__linked_taginfo G__PointingCintLN_RaDec;
extern G__linked_taginfo G__PointingCintLN_TMinuit;
extern G__linked_taginfo G__PointingCintLN_MPointing;
extern G__linked_taginfo G__PointingCintLN_MPointingcLcLdA;
extern G__linked_taginfo G__PointingCintLN_MPointingDev;
extern G__linked_taginfo G__PointingCintLN_MInputStreamID;
extern G__linked_taginfo G__PointingCintLN_MParList;
extern G__linked_taginfo G__PointingCintLN_MTask;
extern G__linked_taginfo G__PointingCintLN_TArrayI;
extern G__linked_taginfo G__PointingCintLN_MRawRunHeader;
extern G__linked_taginfo G__PointingCintLN_MReportStarguider;
extern G__linked_taginfo G__PointingCintLN_MPointingDevCalc;
extern G__linked_taginfo G__PointingCintLN_MTime;
extern G__linked_taginfo G__PointingCintLN_MObservatory;
extern G__linked_taginfo G__PointingCintLN_MPointingPos;
extern G__linked_taginfo G__PointingCintLN_MMcEvt;
extern G__linked_taginfo G__PointingCintLN_MReportDrive;
extern G__linked_taginfo G__PointingCintLN_MPointingPosCalc;
extern G__linked_taginfo G__PointingCintLN_TGraph;
extern G__linked_taginfo G__PointingCintLN_TSpline3;
extern G__linked_taginfo G__PointingCintLN_MDirIter;
extern G__linked_taginfo G__PointingCintLN_MPointingPosInterpolate;
extern G__linked_taginfo G__PointingCintLN_MPointingPosInterpolatecLcLTimeMode_t;
extern G__linked_taginfo G__PointingCintLN_TH2D;
extern G__linked_taginfo G__PointingCintLN_MH;
extern G__linked_taginfo G__PointingCintLN_MHPointing;
extern G__linked_taginfo G__PointingCintLN_MGeomCam;
extern G__linked_taginfo G__PointingCintLN_MParameterD;
extern G__linked_taginfo G__PointingCintLN_MHSrcPosCam;
extern G__linked_taginfo G__PointingCintLN_MSrcPosCam;
extern G__linked_taginfo G__PointingCintLN_MVector3;
extern G__linked_taginfo G__PointingCintLN_MTaskList;
extern G__linked_taginfo G__PointingCintLN_MMcRunHeader;
extern G__linked_taginfo G__PointingCintLN_MMcCorsikaRunHeader;
extern G__linked_taginfo G__PointingCintLN_MSrcPosCalc;
extern G__linked_taginfo G__PointingCintLN_MSrcPosCalccLcLMode_t;
extern G__linked_taginfo G__PointingCintLN_MSrcPosCalccLcLdA;
extern G__linked_taginfo G__PointingCintLN_MSrcPosRndm;
extern G__linked_taginfo G__PointingCintLN_MSrcPosCorrect;
extern G__linked_taginfo G__PointingCintLN_MSrcPosFromModel;

/* STUB derived class for protected member access */
