/********************************************************************
* DataCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DataCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataCint();
extern void G__cpp_setup_inheritanceDataCint();
extern void G__cpp_setup_typetableDataCint();
extern void G__cpp_setup_memvarDataCint();
extern void G__cpp_setup_globalDataCint();
extern void G__cpp_setup_memfuncDataCint();
extern void G__cpp_setup_funcDataCint();
extern void G__set_cpp_environmentDataCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MData.h"
#include "MDataPhrase.h"
#include "MDataArray.h"
#include "MDataElement.h"
#include "MDataMember.h"
#include "MDataValue.h"
#include "MDataList.h"
#include "MDataChain.h"
#include "MDataFormula.h"
#include "DataIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataCintLN_TClass;
extern G__linked_taginfo G__DataCintLN_TBuffer;
extern G__linked_taginfo G__DataCintLN_TMemberInspector;
extern G__linked_taginfo G__DataCintLN_TObject;
extern G__linked_taginfo G__DataCintLN_TString;
extern G__linked_taginfo G__DataCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataCintLN_TObjArray;
extern G__linked_taginfo G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DataCintLN_TEnv;
extern G__linked_taginfo G__DataCintLN_TArrayD;
extern G__linked_taginfo G__DataCintLN_TMethodCall;
extern G__linked_taginfo G__DataCintLN_MParContainer;
extern G__linked_taginfo G__DataCintLN_MParList;
extern G__linked_taginfo G__DataCintLN_MData;
extern G__linked_taginfo G__DataCintLN_MArrayD;
extern G__linked_taginfo G__DataCintLN_TFormula;
extern G__linked_taginfo G__DataCintLN_MDataPhrase;
extern G__linked_taginfo G__DataCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DataCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DataCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DataCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DataCintLN_MDataArray;
extern G__linked_taginfo G__DataCintLN_MHMatrix;
extern G__linked_taginfo G__DataCintLN_MDataElement;
extern G__linked_taginfo G__DataCintLN_MDataMember;
extern G__linked_taginfo G__DataCintLN_MDataMembercLcLdA;
extern G__linked_taginfo G__DataCintLN_MDataValue;
extern G__linked_taginfo G__DataCintLN_TOrdCollection;
extern G__linked_taginfo G__DataCintLN_MDataList;
extern G__linked_taginfo G__DataCintLN_MDataListcLcLSignType_t;
extern G__linked_taginfo G__DataCintLN_MDataListcLcLdA;
extern G__linked_taginfo G__DataCintLN_MDataChain;
extern G__linked_taginfo G__DataCintLN_MDataChaincLcLOperatorType_t;
extern G__linked_taginfo G__DataCintLN_MDataFormula;

/* STUB derived class for protected member access */
