/********************************************************************
* MovieCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MovieCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMovieCint();
extern void G__cpp_setup_inheritanceMovieCint();
extern void G__cpp_setup_typetableMovieCint();
extern void G__cpp_setup_memvarMovieCint();
extern void G__cpp_setup_globalMovieCint();
extern void G__cpp_setup_memfuncMovieCint();
extern void G__cpp_setup_funcMovieCint();
extern void G__set_cpp_environmentMovieCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MMoviePrepare.h"
#include "MMovieData.h"
#include "MMovieWrite.h"
#include "MovieIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MovieCintLN_TClass;
extern G__linked_taginfo G__MovieCintLN_TBuffer;
extern G__linked_taginfo G__MovieCintLN_TMemberInspector;
extern G__linked_taginfo G__MovieCintLN_TObject;
extern G__linked_taginfo G__MovieCintLN_TString;
extern G__linked_taginfo G__MovieCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MovieCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MovieCintLN_TObjArray;
extern G__linked_taginfo G__MovieCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MovieCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MovieCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MovieCintLN_TVirtualPad;
extern G__linked_taginfo G__MovieCintLN_TEnv;
extern G__linked_taginfo G__MovieCintLN_MParContainer;
extern G__linked_taginfo G__MovieCintLN_MInputStreamID;
extern G__linked_taginfo G__MovieCintLN_MParList;
extern G__linked_taginfo G__MovieCintLN_MTask;
extern G__linked_taginfo G__MovieCintLN_MGeomCam;
extern G__linked_taginfo G__MovieCintLN_MExtractor;
extern G__linked_taginfo G__MovieCintLN_MMovieData;
extern G__linked_taginfo G__MovieCintLN_MPedestalCam;
extern G__linked_taginfo G__MovieCintLN_MRawRunHeader;
extern G__linked_taginfo G__MovieCintLN_MCalibConstCam;
extern G__linked_taginfo G__MovieCintLN_MCalibrationRelTimeCam;
extern G__linked_taginfo G__MovieCintLN_MPedestalSubtractedEvt;
extern G__linked_taginfo G__MovieCintLN_MMoviePrepare;
extern G__linked_taginfo G__MovieCintLN_MCamEvent;
extern G__linked_taginfo G__MovieCintLN_TGraph;
extern G__linked_taginfo G__MovieCintLN_MSpline3;
extern G__linked_taginfo G__MovieCintLN_TH1;
extern G__linked_taginfo G__MovieCintLN_TASImage;
extern G__linked_taginfo G__MovieCintLN_MMcEvt;
extern G__linked_taginfo G__MovieCintLN_MSignalCam;
extern G__linked_taginfo G__MovieCintLN_MRawEvtHeader;
extern G__linked_taginfo G__MovieCintLN_MBadPixelsCam;
extern G__linked_taginfo G__MovieCintLN_MMovieWrite;

/* STUB derived class for protected member access */
