/********************************************************************
* SimCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SimCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimCint();
extern void G__cpp_setup_inheritanceSimCint();
extern void G__cpp_setup_typetableSimCint();
extern void G__cpp_setup_memvarSimCint();
extern void G__cpp_setup_globalSimCint();
extern void G__cpp_setup_memfuncSimCint();
extern void G__cpp_setup_funcSimCint();
extern void G__set_cpp_environmentSimCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MPhotonData.h"
#include "MPhotonEvent.h"
#include "MHPhotonEvent.h"
#include "MSimMMCS.h"
#include "MSimAtmosphere.h"
#include "MSimAbsorption.h"
#include "MSimPointingPos.h"
#include "SimIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimCintLN_TClass;
extern G__linked_taginfo G__SimCintLN_TBuffer;
extern G__linked_taginfo G__SimCintLN_TMemberInspector;
extern G__linked_taginfo G__SimCintLN_TObject;
extern G__linked_taginfo G__SimCintLN_TString;
extern G__linked_taginfo G__SimCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SimCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCintLN_TClonesArray;
extern G__linked_taginfo G__SimCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SimCintLN_TEnv;
extern G__linked_taginfo G__SimCintLN_MParContainer;
extern G__linked_taginfo G__SimCintLN_MMcEvtBasic;
extern G__linked_taginfo G__SimCintLN_MMcEvtBasiccLcLParticleId_t;
extern G__linked_taginfo G__SimCintLN_TVector2;
extern G__linked_taginfo G__SimCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SimCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SimCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__SimCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__SimCintLN_TVector3;
extern G__linked_taginfo G__SimCintLN_TQuaternion;
extern G__linked_taginfo G__SimCintLN_MCorsikaRunHeader;
extern G__linked_taginfo G__SimCintLN_MPhotonData;
extern G__linked_taginfo G__SimCintLN_MCorsikaFormat;
extern G__linked_taginfo G__SimCintLN_MPhotonEvent;
extern G__linked_taginfo G__SimCintLN_MPhotonStatistics;
extern G__linked_taginfo G__SimCintLN_MParList;
extern G__linked_taginfo G__SimCintLN_TH1F;
extern G__linked_taginfo G__SimCintLN_TH2F;
extern G__linked_taginfo G__SimCintLN_TProfile2D;
extern G__linked_taginfo G__SimCintLN_MH;
extern G__linked_taginfo G__SimCintLN_MHPhotonEvent;
extern G__linked_taginfo G__SimCintLN_MInputStreamID;
extern G__linked_taginfo G__SimCintLN_MTask;
extern G__linked_taginfo G__SimCintLN_MMcEvt;
extern G__linked_taginfo G__SimCintLN_MPointingPos;
extern G__linked_taginfo G__SimCintLN_MCorsikaEvtHeader;
extern G__linked_taginfo G__SimCintLN_MMcRunHeader;
extern G__linked_taginfo G__SimCintLN_MSimMMCS;
extern G__linked_taginfo G__SimCintLN_MAtmosphere;
extern G__linked_taginfo G__SimCintLN_MSimAtmosphere;
extern G__linked_taginfo G__SimCintLN_MParSpline;
extern G__linked_taginfo G__SimCintLN_MSimAbsorption;
extern G__linked_taginfo G__SimCintLN_MSimPointingPos;

/* STUB derived class for protected member access */
