/********************************************************************
* RawCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RawCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRawCint();
extern void G__cpp_setup_inheritanceRawCint();
extern void G__cpp_setup_typetableRawCint();
extern void G__cpp_setup_memvarRawCint();
extern void G__cpp_setup_globalRawCint();
extern void G__cpp_setup_memfuncRawCint();
extern void G__cpp_setup_funcRawCint();
extern void G__set_cpp_environmentRawCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MRawRunHeader.h"
#include "MRawEvtHeader.h"
#include "MRawEvtData.h"
#include "MRawEvtPixelIter.h"
#include "MRawCrateArray.h"
#include "MRawCrateData.h"
#include "MRawBoardsFACT.h"
#include "MRawRead.h"
#include "MRawFileRead.h"
#include "MRawFitsRead.h"
#include "RawIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RawCintLN_TClass;
extern G__linked_taginfo G__RawCintLN_TBuffer;
extern G__linked_taginfo G__RawCintLN_TMemberInspector;
extern G__linked_taginfo G__RawCintLN_TObject;
extern G__linked_taginfo G__RawCintLN_TString;
extern G__linked_taginfo G__RawCintLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__RawCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RawCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RawCintLN_TList;
extern G__linked_taginfo G__RawCintLN_TClonesArray;
extern G__linked_taginfo G__RawCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RawCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RawCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RawCintLN_fits;
extern G__linked_taginfo G__RawCintLN_TEnv;
extern G__linked_taginfo G__RawCintLN_MParContainer;
extern G__linked_taginfo G__RawCintLN_MTime;
extern G__linked_taginfo G__RawCintLN_MArrayS;
extern G__linked_taginfo G__RawCintLN_MRawRunHeader;
extern G__linked_taginfo G__RawCintLN_MRawRunHeadercLcLdA;
extern G__linked_taginfo G__RawCintLN_MGeomCam;
extern G__linked_taginfo G__RawCintLN_MCamEvent;
extern G__linked_taginfo G__RawCintLN_MArrayB;
extern G__linked_taginfo G__RawCintLN_MRawEvtHeader;
extern G__linked_taginfo G__RawCintLN_MRawEvtHeadercLcLCLColor_t;
extern G__linked_taginfo G__RawCintLN_MRawCrateArray;
extern G__linked_taginfo G__RawCintLN_TArrayC;
extern G__linked_taginfo G__RawCintLN_MArrayI;
extern G__linked_taginfo G__RawCintLN_MRawEvtData;
extern G__linked_taginfo G__RawCintLN_MRawEvtPixelIter;
extern G__linked_taginfo G__RawCintLN_MRawCrateData;
extern G__linked_taginfo G__RawCintLN_MRawBoardsFACT;
extern G__linked_taginfo G__RawCintLN_MRawFitsRead;
extern G__linked_taginfo G__RawCintLN_MInputStreamID;
extern G__linked_taginfo G__RawCintLN_MParList;
extern G__linked_taginfo G__RawCintLN_MTask;
extern G__linked_taginfo G__RawCintLN_MRead;
extern G__linked_taginfo G__RawCintLN_MRawRead;
extern G__linked_taginfo G__RawCintLN_MRawFileRead;
extern G__linked_taginfo G__RawCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__RawCintLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RawCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__RawCintLN_reverse_iteratorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
