#!/bin/sh
#
# ========================================================================
#
# *
# * This file is part of MARS, the MAGIC Analysis and Reconstruction
# * Software. It is distributed to you in the hope that it can be a useful
# * and timesaving tool in analysing Data of imaging Cerenkov telescopes.
# * It is distributed WITHOUT ANY WARRANTY.
# *
# * Permission to use, copy, modify and distribute this software and its
# * documentation for any purpose is hereby granted without fee,
# * provided that the above copyright notice appear in all copies and
# * that both that copyright notice and this permission notice appear
# * in supporting documentation. It is provided "as is" without express
# * or implied warranty.
# *
#
#
#   Author(s): Daniela Dorner  05/2005 <mailto:dorner@astro.uni-wuerzburg.de>
#
#   Copyright: MAGIC Software Development, 2000-2006
#
#
# ========================================================================
#
# This a resource file for the scripts, in which the standard paths and 
# functions, which are needed more often are stored. 
#

olds=0
cnt=0
sequences=`cat /home/bla/not-sequenced.anymore.2006.10.06.19.20.34 | cut -c 19-23`
for sequence in $sequences
do 
#   echo "v: $sequence $cnt"
   if ! [ $sequence -eq $olds ]
   then 
       if [ $cnt -gt 10 ]
       then 
          echo "seq: $olds $cnt"
       fi
       olds=$sequence
       cnt=0
   fi
   cnt=`echo $cnt + 1 | bc`
done
