/********************************************************************
* JobsCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JobsCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJobsCint();
extern void G__cpp_setup_inheritanceJobsCint();
extern void G__cpp_setup_typetableJobsCint();
extern void G__cpp_setup_memvarJobsCint();
extern void G__cpp_setup_globalJobsCint();
extern void G__cpp_setup_memfuncJobsCint();
extern void G__cpp_setup_funcJobsCint();
extern void G__set_cpp_environmentJobsCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MSequence.h"
#include "MSequenceSQL.h"
#include "MDataSet.h"
#include "MJob.h"
#include "MJSimulation.h"
#include "MJSimReflector.h"
#include "MJPedestal.h"
#include "MJCalib.h"
#include "MJCalibration.h"
#include "MJCalibrateSignal.h"
#include "MJMerpp.h"
#include "MJStar.h"
#include "MJCut.h"
#include "MJSpectrum.h"
#include "JobsIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JobsCintLN_TClass;
extern G__linked_taginfo G__JobsCintLN_TBuffer;
extern G__linked_taginfo G__JobsCintLN_TMemberInspector;
extern G__linked_taginfo G__JobsCintLN_TObject;
extern G__linked_taginfo G__JobsCintLN_TCollection;
extern G__linked_taginfo G__JobsCintLN_TString;
extern G__linked_taginfo G__JobsCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__JobsCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JobsCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JobsCintLN_TList;
extern G__linked_taginfo G__JobsCintLN_TObjArray;
extern G__linked_taginfo G__JobsCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JobsCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JobsCintLN_TArrayI;
extern G__linked_taginfo G__JobsCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JobsCintLN_TEnv;
extern G__linked_taginfo G__JobsCintLN_TArrayD;
extern G__linked_taginfo G__JobsCintLN_MStatusDisplay;
extern G__linked_taginfo G__JobsCintLN_MParContainer;
extern G__linked_taginfo G__JobsCintLN_MTime;
extern G__linked_taginfo G__JobsCintLN_MDirIter;
extern G__linked_taginfo G__JobsCintLN_MSequence;
extern G__linked_taginfo G__JobsCintLN_MSequenceSQL;
extern G__linked_taginfo G__JobsCintLN_MSequencecLcLLightCondition_t;
extern G__linked_taginfo G__JobsCintLN_MSequencecLcLFileExt_t;
extern G__linked_taginfo G__JobsCintLN_MSequencecLcLRunType_t;
extern G__linked_taginfo G__JobsCintLN_MSequencecLcLdA;
extern G__linked_taginfo G__JobsCintLN_MSequencecLcLFileType_t;
extern G__linked_taginfo G__JobsCintLN_TSQLRow;
extern G__linked_taginfo G__JobsCintLN_TSQLResult;
extern G__linked_taginfo G__JobsCintLN_MSQLMagic;
extern G__linked_taginfo G__JobsCintLN_TChain;
extern G__linked_taginfo G__JobsCintLN_MRead;
extern G__linked_taginfo G__JobsCintLN_MPointingPos;
extern G__linked_taginfo G__JobsCintLN_MDataSet;
extern G__linked_taginfo G__JobsCintLN_MEnv;
extern G__linked_taginfo G__JobsCintLN_MEvtLoop;
extern G__linked_taginfo G__JobsCintLN_MJob;
extern G__linked_taginfo G__JobsCintLN_MJobcLcLdA;
extern G__linked_taginfo G__JobsCintLN_MHn;
extern G__linked_taginfo G__JobsCintLN_MArgs;
extern G__linked_taginfo G__JobsCintLN_MParList;
extern G__linked_taginfo G__JobsCintLN_MWriteRootFile;
extern G__linked_taginfo G__JobsCintLN_MWriteFitsFile;
extern G__linked_taginfo G__JobsCintLN_MRawRunHeader;
extern G__linked_taginfo G__JobsCintLN_MJSimulation;
extern G__linked_taginfo G__JobsCintLN_MJSimulationcLcLMode_t;
extern G__linked_taginfo G__JobsCintLN_MJSimReflector;
extern G__linked_taginfo G__JobsCintLN_MJSimReflectorcLcLMode_t;
extern G__linked_taginfo G__JobsCintLN_MJCalib;
extern G__linked_taginfo G__JobsCintLN_MJCalibcLcLStorage_t;
extern G__linked_taginfo G__JobsCintLN_MJCalibcLcLDevice_t;
extern G__linked_taginfo G__JobsCintLN_MBadPixelsCam;
extern G__linked_taginfo G__JobsCintLN_MPedestalCam;
extern G__linked_taginfo G__JobsCintLN_TH1;
extern G__linked_taginfo G__JobsCintLN_TH1D;
extern G__linked_taginfo G__JobsCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__JobsCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__JobsCintLN_TF1;
extern G__linked_taginfo G__JobsCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__JobsCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__JobsCintLN_TH2D;
extern G__linked_taginfo G__JobsCintLN_MH;
extern G__linked_taginfo G__JobsCintLN_MCalibrationCam;
extern G__linked_taginfo G__JobsCintLN_MCalibrationCamcLcLPulserColor_t;
extern G__linked_taginfo G__JobsCintLN_MHCamera;
extern G__linked_taginfo G__JobsCintLN_MExtractor;
extern G__linked_taginfo G__JobsCintLN_MJPedestal;
extern G__linked_taginfo G__JobsCintLN_MJPedestalcLcLDisplay_t;
extern G__linked_taginfo G__JobsCintLN_MJPedestalcLcLExtract_t;
extern G__linked_taginfo G__JobsCintLN_MJPedestalcLcLExtraction;
extern G__linked_taginfo G__JobsCintLN_MCalibrationQECam;
extern G__linked_taginfo G__JobsCintLN_MCalibrationChargeCam;
extern G__linked_taginfo G__JobsCintLN_MCalibrationBlindCam;
extern G__linked_taginfo G__JobsCintLN_MCalibrationRelTimeCam;
extern G__linked_taginfo G__JobsCintLN_MCalibrationChargePINDiode;
extern G__linked_taginfo G__JobsCintLN_MTask;
extern G__linked_taginfo G__JobsCintLN_MExtractTime;
extern G__linked_taginfo G__JobsCintLN_MExtractBlindPixel;
extern G__linked_taginfo G__JobsCintLN_MHCalibrationChargeBlindCam;
extern G__linked_taginfo G__JobsCintLN_MJCalibration;
extern G__linked_taginfo G__JobsCintLN_MJCalibrationcLcLDisplay_t;
extern G__linked_taginfo G__JobsCintLN_MJCalibrationcLcLdA;
extern G__linked_taginfo G__JobsCintLN_MJCalibrateSignal;
extern G__linked_taginfo G__JobsCintLN_MReportFileReadCC;
extern G__linked_taginfo G__JobsCintLN_MFilter;
extern G__linked_taginfo G__JobsCintLN_MRawFileRead;
extern G__linked_taginfo G__JobsCintLN_MJMerpp;
extern G__linked_taginfo G__JobsCintLN_MJStar;
extern G__linked_taginfo G__JobsCintLN_MHAlpha;
extern G__linked_taginfo G__JobsCintLN_MHSrcPosCam;
extern G__linked_taginfo G__JobsCintLN_MJCut;
extern G__linked_taginfo G__JobsCintLN_MHEnergyEst;
extern G__linked_taginfo G__JobsCintLN_MAlphaFitter;
extern G__linked_taginfo G__JobsCintLN_MStatusArray;
extern G__linked_taginfo G__JobsCintLN_MHCollectionArea;
extern G__linked_taginfo G__JobsCintLN_MMcSpectrumWeight;
extern G__linked_taginfo G__JobsCintLN_MJSpectrum;

/* STUB derived class for protected member access */
