/********************************************************************
* ElectronicsCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ElectronicsCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableElectronicsCint();
extern void G__cpp_setup_inheritanceElectronicsCint();
extern void G__cpp_setup_typetableElectronicsCint();
extern void G__cpp_setup_memvarElectronicsCint();
extern void G__cpp_setup_globalElectronicsCint();
extern void G__cpp_setup_memfuncElectronicsCint();
extern void G__cpp_setup_funcElectronicsCint();
extern void G__set_cpp_environmentElectronicsCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MAvalanchePhotoDiode.h"
#include "MAnalogSignal.h"
#include "MAnalogChannels.h"
#include "MDigitalSignal.h"
#include "ElectronicsIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ElectronicsCintLN_TClass;
extern G__linked_taginfo G__ElectronicsCintLN_TBuffer;
extern G__linked_taginfo G__ElectronicsCintLN_TMemberInspector;
extern G__linked_taginfo G__ElectronicsCintLN_TObject;
extern G__linked_taginfo G__ElectronicsCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ElectronicsCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElectronicsCintLN_TObjArray;
extern G__linked_taginfo G__ElectronicsCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ElectronicsCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElectronicsCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ElectronicsCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ElectronicsCintLN_TF1;
extern G__linked_taginfo G__ElectronicsCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ElectronicsCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ElectronicsCintLN_TH2F;
extern G__linked_taginfo G__ElectronicsCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ElectronicsCintLN_TSortedList;
extern G__linked_taginfo G__ElectronicsCintLN_APD;
extern G__linked_taginfo G__ElectronicsCintLN_Afterpulse;
extern G__linked_taginfo G__ElectronicsCintLN_MArray;
extern G__linked_taginfo G__ElectronicsCintLN_MArrayF;
extern G__linked_taginfo G__ElectronicsCintLN_MSpline3;
extern G__linked_taginfo G__ElectronicsCintLN_MAnalogSignal;
extern G__linked_taginfo G__ElectronicsCintLN_MParContainer;
extern G__linked_taginfo G__ElectronicsCintLN_MAnalogChannels;
extern G__linked_taginfo G__ElectronicsCintLN_MDigitalSignal;

/* STUB derived class for protected member access */
