/********************************************************************
* ReportCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ReportCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableReportCint();
extern void G__cpp_setup_inheritanceReportCint();
extern void G__cpp_setup_typetableReportCint();
extern void G__cpp_setup_memvarReportCint();
extern void G__cpp_setup_globalReportCint();
extern void G__cpp_setup_memfuncReportCint();
extern void G__cpp_setup_funcReportCint();
extern void G__set_cpp_environmentReportCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MReport.h"
#include "MReportCC.h"
#include "MReportRec.h"
#include "MReportRun.h"
#include "MReportDAQ.h"
#include "MReportHelp.h"
#include "MReportDrive.h"
#include "MReportCamera.h"
#include "MReportTrigger.h"
#include "MReportCurrents.h"
#include "MReportFitsRead.h"
#include "MReportFileRead.h"
#include "MReportFileReadCC.h"
#include "MReportStarguider.h"
#include "MReportPyrometer.h"
#include "MReportRates.h"
#include "MReportTemperatures.h"
#include "MReportHumidity.h"
#include "ReportIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ReportCintLN_TClass;
extern G__linked_taginfo G__ReportCintLN_TBuffer;
extern G__linked_taginfo G__ReportCintLN_TMemberInspector;
extern G__linked_taginfo G__ReportCintLN_TObject;
extern G__linked_taginfo G__ReportCintLN_TString;
extern G__linked_taginfo G__ReportCintLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ReportCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ReportCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ReportCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ReportCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ReportCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ReportCintLN_fits;
extern G__linked_taginfo G__ReportCintLN_MLog;
extern G__linked_taginfo G__ReportCintLN_MParContainer;
extern G__linked_taginfo G__ReportCintLN_MTime;
extern G__linked_taginfo G__ReportCintLN_MParList;
extern G__linked_taginfo G__ReportCintLN_MReport;
extern G__linked_taginfo G__ReportCintLN_MReportRec;
extern G__linked_taginfo G__ReportCintLN_MCameraTH;
extern G__linked_taginfo G__ReportCintLN_MCameraTD;
extern G__linked_taginfo G__ReportCintLN_MCameraRecTemp;
extern G__linked_taginfo G__ReportCintLN_MReportWeather;
extern G__linked_taginfo G__ReportCintLN_MReportCC;
extern G__linked_taginfo G__ReportCintLN_MReportRun;
extern G__linked_taginfo G__ReportCintLN_MReportDAQ;
extern G__linked_taginfo G__ReportCintLN_MReportHelp;
extern G__linked_taginfo G__ReportCintLN_MReportDrive;
extern G__linked_taginfo G__ReportCintLN_MCameraCooling;
extern G__linked_taginfo G__ReportCintLN_MCameraLids;
extern G__linked_taginfo G__ReportCintLN_MCameraHV;
extern G__linked_taginfo G__ReportCintLN_MCameraDC;
extern G__linked_taginfo G__ReportCintLN_MCameraLV;
extern G__linked_taginfo G__ReportCintLN_MCameraAUX;
extern G__linked_taginfo G__ReportCintLN_MCameraCalibration;
extern G__linked_taginfo G__ReportCintLN_MCameraActiveLoad;
extern G__linked_taginfo G__ReportCintLN_MCameraCentralPix;
extern G__linked_taginfo G__ReportCintLN_MReportCamera;
extern G__linked_taginfo G__ReportCintLN_MTriggerIPR;
extern G__linked_taginfo G__ReportCintLN_MTriggerCell;
extern G__linked_taginfo G__ReportCintLN_MTriggerBit;
extern G__linked_taginfo G__ReportCintLN_MTriggerPrescFact;
extern G__linked_taginfo G__ReportCintLN_MTriggerLiveTime;
extern G__linked_taginfo G__ReportCintLN_MReportTrigger;
extern G__linked_taginfo G__ReportCintLN_MReportCurrents;
extern G__linked_taginfo G__ReportCintLN_MInputStreamID;
extern G__linked_taginfo G__ReportCintLN_MTask;
extern G__linked_taginfo G__ReportCintLN_THashTable;
extern G__linked_taginfo G__ReportCintLN_MReportFitsRead;
extern G__linked_taginfo G__ReportCintLN_MReportFitsReadcLcLdA;
extern G__linked_taginfo G__ReportCintLN_MReportFileRead;
extern G__linked_taginfo G__ReportCintLN_MReportFileReadcLcLdA;
extern G__linked_taginfo G__ReportCintLN_MReportFileReadCC;
extern G__linked_taginfo G__ReportCintLN_TVector2;
extern G__linked_taginfo G__ReportCintLN_MReportStarguider;
extern G__linked_taginfo G__ReportCintLN_MReportStarguidercLcLdA;
extern G__linked_taginfo G__ReportCintLN_MReportPyrometer;
extern G__linked_taginfo G__ReportCintLN_MReportRates;
extern G__linked_taginfo G__ReportCintLN_MReportTemperatures;
extern G__linked_taginfo G__ReportCintLN_MReportHumidity;

/* STUB derived class for protected member access */
