#!/bin/bash
#
# ========================================================================
#
# *
# * This file is part of MARS, the MAGIC Analysis and Reconstruction
# * Software. It is distributed to you in the hope that it can be a useful
# * and timesaving tool in analysing Data of imaging Cerenkov telescopes.
# * It is distributed WITHOUT ANY WARRANTY.
# *
# * Permission to use, copy, modify and distribute this software and its
# * documentation for any purpose is hereby granted without fee,
# * provided that the above copyright notice appear in all copies and
# * that both that copyright notice and this permission notice appear
# * in supporting documentation. It is provided "as is" without express
# * or implied warranty.
# *
#
#
#   Author(s): Daniela Dorner  08/2006 <mailto:dorner@astro.uni-wuerzburg.de>
#
#   Copyright: MAGIC Software Development, 2000-2007
#
#
# ========================================================================
#
# This script checks, if there are WARNs or ERRORs in the processlog of 
# the last night and sends them to the emailadresse(s) in $erradr
#

source `dirname $0`/sourcefile
printprocesslog "INFO starting $0"

oldprocesslog=$processlogpath/process`date +%F --date="-1day"`.log

if grep WARN $oldprocesslog >/dev/null
then 
   grep WARN $oldprocesslog | mail -s 'found warnings in '$oldprocesslog $erradrs
fi

if grep ERROR $oldprocesslog >/dev/null
then 
   grep ERROR $oldprocesslog | mail -s 'found errors in '$oldprocesslog $erradrs
fi

printprocesslog "INFO finished $0"

