#!/bin/sh
#
# ========================================================================
#
# *
# * This file is part of MARS, the MAGIC Analysis and Reconstruction
# * Software. It is distributed to you in the hope that it can be a useful
# * and timesaving tool in analysing Data of imaging Cerenkov telescopes.
# * It is distributed WITHOUT ANY WARRANTY.
# *
# * Permission to use, copy, modify and distribute this software and its
# * documentation for any purpose is hereby granted without fee,
# * provided that the above copyright notice appear in all copies and
# * that both that copyright notice and this permission notice appear
# * in supporting documentation. It is provided "as is" without express
# * or implied warranty.
# *
#
#
#   Author(s): Daniela Dorner  08/2004 <mailto:dorner@astro.uni-wuerzburg.de>
#
#   Copyright: MAGIC Software Development, 2000-2007
#
#
# ========================================================================
#
# This script launches the filling of the results of star into the db 
# for all sequences of which the results are not yet in the database.
#
# After checking if the script is already running the todolist is written. 
# Then for each sequence in the todo list the star results are filled 
# into the table Star in the database using the macro fillstar.C
# If this was successful, the status is inserted into the database using 
# the function setstatus.
#

source `dirname $0`/sourcefile
printprocesslog "INFO starting $0"
program=fillstar
column=fFillStar

set -C

# check if the script is already running
lockfile=$lockpath/lock-$program.txt
checklock 

# get todo list
gettodo 

cd $mars

# run fillstar for sequences
for (( s=0 ; s < $num ; s++ ))
do
   sequence=${primaries[$s+$s]}
   telnum=${primaries[$s+$s+1]}
   printprocesslog "INFO starting $program for sequence $sequence"
   no=`printf %08d $sequence | cut -c 0-4`
   no2=`printf %08d $sequence`
   path="$datapath/star/$no/$no2"
   starfile=$path/star$no2.root
   fillstarlogpath=$logpath/$program/$no
   makedir $fillstarlogpath 
   fillstarlog=$fillstarlogpath/$program-$sequence.log

   setstatus "start" 

   check2=`root -q -b $macrospath/fillstar.C+\("\"$starfile\""\,kFALSE\) | tee $fillstarlog | intgrep`
   case $check2 in
      1)   printprocesslog "INFO done fillstar successfully for sequence $sequence (check2=$check2)"
           ;;
      0)   printprocesslog "WARN connection to DB failed (check2=$check2)"
           check="no"
           ;;
      *)   printprocesslog "ERROR fillstar failed for sequence $sequence (check2=$check2)"
           com=$Ffillstar
           check=$check2
           ;;
   esac
   
   setstatus "stop" 
done

finish 

