/********************************************************************
* MuonCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MuonCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMuonCint();
extern void G__cpp_setup_inheritanceMuonCint();
extern void G__cpp_setup_typetableMuonCint();
extern void G__cpp_setup_memvarMuonCint();
extern void G__cpp_setup_globalMuonCint();
extern void G__cpp_setup_memfuncMuonCint();
extern void G__cpp_setup_funcMuonCint();
extern void G__set_cpp_environmentMuonCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MMuonSearchPar.h"
#include "MMuonSearchParCalc.h"
#include "MMuonCalibPar.h"
#include "MMuonCalibParCalc.h"
#include "MHMuonPar.h"
#include "MHSingleMuon.h"
#include "MMuonSetup.h"
#include "MuonIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MuonCintLN_TClass;
extern G__linked_taginfo G__MuonCintLN_TBuffer;
extern G__linked_taginfo G__MuonCintLN_TMemberInspector;
extern G__linked_taginfo G__MuonCintLN_TObject;
extern G__linked_taginfo G__MuonCintLN_TString;
extern G__linked_taginfo G__MuonCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MuonCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MuonCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MuonCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MuonCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MuonCintLN_TEnv;
extern G__linked_taginfo G__MuonCintLN_MParContainer;
extern G__linked_taginfo G__MuonCintLN_MArrayF;
extern G__linked_taginfo G__MuonCintLN_MHillas;
extern G__linked_taginfo G__MuonCintLN_MGeomCam;
extern G__linked_taginfo G__MuonCintLN_MSignalCam;
extern G__linked_taginfo G__MuonCintLN_MMuonSearchPar;
extern G__linked_taginfo G__MuonCintLN_MInputStreamID;
extern G__linked_taginfo G__MuonCintLN_MParList;
extern G__linked_taginfo G__MuonCintLN_MTask;
extern G__linked_taginfo G__MuonCintLN_MMuonSearchParCalc;
extern G__linked_taginfo G__MuonCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MuonCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MuonCintLN_TH1F;
extern G__linked_taginfo G__MuonCintLN_MMuonCalibPar;
extern G__linked_taginfo G__MuonCintLN_MMuonSetup;
extern G__linked_taginfo G__MuonCintLN_MHSingleMuon;
extern G__linked_taginfo G__MuonCintLN_MMuonCalibParCalc;
extern G__linked_taginfo G__MuonCintLN_TProfile;
extern G__linked_taginfo G__MuonCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MuonCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MuonCintLN_MH;
extern G__linked_taginfo G__MuonCintLN_MHMuonPar;

/* STUB derived class for protected member access */
