/********************************************************************
* SignalCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SignalCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSignalCint();
extern void G__cpp_setup_inheritanceSignalCint();
extern void G__cpp_setup_typetableSignalCint();
extern void G__cpp_setup_memvarSignalCint();
extern void G__cpp_setup_globalSignalCint();
extern void G__cpp_setup_memfuncSignalCint();
extern void G__cpp_setup_funcSignalCint();
extern void G__set_cpp_environmentSignalCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MExtractedSignalCam.h"
#include "MExtractedSignalPix.h"
#include "MExtractedSignalPINDiode.h"
#include "MExtractedSignalBlindPixel.h"
#include "MExtractor.h"
#include "MExtractPINDiode.h"
#include "MExtractBlindPixel.h"
#include "MExtractTime.h"
#include "MExtractTimeAndCharge.h"
#include "MExtractTimeAndChargeSpline.h"
#include "MExtractTimeAndChargeDigitalFilter.h"
#include "MExtractFACT.h"
#include "MSignalCam.h"
#include "MSignalPix.h"
#include "MSignalCalc.h"
#include "MFilterData.h"
#include "MTreatSaturation.h"
#include "MArrivalTimeCam.h"
#include "MArrivalTimePix.h"
#include "SignalIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SignalCintLN_TClass;
extern G__linked_taginfo G__SignalCintLN_TBuffer;
extern G__linked_taginfo G__SignalCintLN_TMemberInspector;
extern G__linked_taginfo G__SignalCintLN_TObject;
extern G__linked_taginfo G__SignalCintLN_TString;
extern G__linked_taginfo G__SignalCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SignalCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SignalCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SignalCintLN_TClonesArray;
extern G__linked_taginfo G__SignalCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SignalCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SignalCintLN_TIterator;
extern G__linked_taginfo G__SignalCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SignalCintLN_TEnv;
extern G__linked_taginfo G__SignalCintLN_MLog;
extern G__linked_taginfo G__SignalCintLN_MParContainer;
extern G__linked_taginfo G__SignalCintLN_MGeomCam;
extern G__linked_taginfo G__SignalCintLN_MCamEvent;
extern G__linked_taginfo G__SignalCintLN_MExtractedSignalPix;
extern G__linked_taginfo G__SignalCintLN_MExtractedSignalCam;
extern G__linked_taginfo G__SignalCintLN_MExtractedSignalPINDiode;
extern G__linked_taginfo G__SignalCintLN_TArrayI;
extern G__linked_taginfo G__SignalCintLN_TArrayF;
extern G__linked_taginfo G__SignalCintLN_MInputStreamID;
extern G__linked_taginfo G__SignalCintLN_MParList;
extern G__linked_taginfo G__SignalCintLN_MTask;
extern G__linked_taginfo G__SignalCintLN_MRawEvtData;
extern G__linked_taginfo G__SignalCintLN_MRawRunHeader;
extern G__linked_taginfo G__SignalCintLN_MPedestalSubtractedEvt;
extern G__linked_taginfo G__SignalCintLN_MExtractor;
extern G__linked_taginfo G__SignalCintLN_MArrayI;
extern G__linked_taginfo G__SignalCintLN_MArrayF;
extern G__linked_taginfo G__SignalCintLN_MCalibrationBlindCam;
extern G__linked_taginfo G__SignalCintLN_MExtractedSignalBlindPixel;
extern G__linked_taginfo G__SignalCintLN_MExtractBlindPixel;
extern G__linked_taginfo G__SignalCintLN_MExtractBlindPixelcLcLExtractionType_t;
extern G__linked_taginfo G__SignalCintLN_MExtractBlindPixelcLcLDataType_t;
extern G__linked_taginfo G__SignalCintLN_TH1F;
extern G__linked_taginfo G__SignalCintLN_MExtractPINDiode;
extern G__linked_taginfo G__SignalCintLN_MArrivalTimeCam;
extern G__linked_taginfo G__SignalCintLN_MExtractTime;
extern G__linked_taginfo G__SignalCintLN_MExtractTimeAndCharge;
extern G__linked_taginfo G__SignalCintLN_MExtralgoSpline;
extern G__linked_taginfo G__SignalCintLN_MExtralgoSplinecLcLExtractionType_t;
extern G__linked_taginfo G__SignalCintLN_MExtractTimeAndChargeSpline;
extern G__linked_taginfo G__SignalCintLN_MCalibrationPattern;
extern G__linked_taginfo G__SignalCintLN_MExtractTimeAndChargeDigitalFilter;
extern G__linked_taginfo G__SignalCintLN_MExtractFACT;
extern G__linked_taginfo G__SignalCintLN_TObjArrayIter;
extern G__linked_taginfo G__SignalCintLN_MSignalPix;
extern G__linked_taginfo G__SignalCintLN_MSignalCamIter;
extern G__linked_taginfo G__SignalCintLN_MSignalCam;
extern G__linked_taginfo G__SignalCintLN_MPedestalCam;
extern G__linked_taginfo G__SignalCintLN_MSignalCalc;
extern G__linked_taginfo G__SignalCintLN_MFilterData;
extern G__linked_taginfo G__SignalCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__SignalCintLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SignalCintLN_MTreatSaturation;
extern G__linked_taginfo G__SignalCintLN_MArrivalTimePix;

/* STUB derived class for protected member access */
