/********************************************************************
* FBaseCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FBaseCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFBaseCint();
extern void G__cpp_setup_inheritanceFBaseCint();
extern void G__cpp_setup_typetableFBaseCint();
extern void G__cpp_setup_memvarFBaseCint();
extern void G__cpp_setup_globalFBaseCint();
extern void G__cpp_setup_memfuncFBaseCint();
extern void G__cpp_setup_funcFBaseCint();
extern void G__set_cpp_environmentFBaseCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MF.h"
#include "MFDataPhrase.h"
#include "MFilterList.h"
#include "MFEventSelector.h"
#include "MFEventSelector2.h"
#include "MFDataChain.h"
#include "MFDataMember.h"
#include "MFRealTimePeriod.h"
#include "FBaseIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FBaseCintLN_TClass;
extern G__linked_taginfo G__FBaseCintLN_TBuffer;
extern G__linked_taginfo G__FBaseCintLN_TMemberInspector;
extern G__linked_taginfo G__FBaseCintLN_TObject;
extern G__linked_taginfo G__FBaseCintLN_TCollection;
extern G__linked_taginfo G__FBaseCintLN_TString;
extern G__linked_taginfo G__FBaseCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__FBaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FBaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FBaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FBaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FBaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FBaseCintLN_TCanvas;
extern G__linked_taginfo G__FBaseCintLN_TEnv;
extern G__linked_taginfo G__FBaseCintLN_TArrayD;
extern G__linked_taginfo G__FBaseCintLN_MParContainer;
extern G__linked_taginfo G__FBaseCintLN_MInputStreamID;
extern G__linked_taginfo G__FBaseCintLN_MFilter;
extern G__linked_taginfo G__FBaseCintLN_MParList;
extern G__linked_taginfo G__FBaseCintLN_MTask;
extern G__linked_taginfo G__FBaseCintLN_MF;
extern G__linked_taginfo G__FBaseCintLN_MData;
extern G__linked_taginfo G__FBaseCintLN_MFDataPhrase;
extern G__linked_taginfo G__FBaseCintLN_TOrdCollection;
extern G__linked_taginfo G__FBaseCintLN_MFilterList;
extern G__linked_taginfo G__FBaseCintLN_MFilterListcLcLFilterType_t;
extern G__linked_taginfo G__FBaseCintLN_MFilterListcLcLdA;
extern G__linked_taginfo G__FBaseCintLN_MFEventSelector;
extern G__linked_taginfo G__FBaseCintLN_MFEventSelectorcLcLdA;
extern G__linked_taginfo G__FBaseCintLN_TArrayL;
extern G__linked_taginfo G__FBaseCintLN_MDataChain;
extern G__linked_taginfo G__FBaseCintLN_TH1;
extern G__linked_taginfo G__FBaseCintLN_MH3;
extern G__linked_taginfo G__FBaseCintLN_MRead;
extern G__linked_taginfo G__FBaseCintLN_MFEventSelector2;
extern G__linked_taginfo G__FBaseCintLN_MFDataChain;
extern G__linked_taginfo G__FBaseCintLN_MFDataChaincLcLFilterType_t;
extern G__linked_taginfo G__FBaseCintLN_MDataMember;
extern G__linked_taginfo G__FBaseCintLN_MFDataMember;
extern G__linked_taginfo G__FBaseCintLN_MFDataMembercLcLFilterType_t;
extern G__linked_taginfo G__FBaseCintLN_MFDataMembercLcLdA;
extern G__linked_taginfo G__FBaseCintLN_MFRealTimePeriod;

/* STUB derived class for protected member access */
