/********************************************************************
* TriggerCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TriggerCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTriggerCint();
extern void G__cpp_setup_inheritanceTriggerCint();
extern void G__cpp_setup_typetableTriggerCint();
extern void G__cpp_setup_memvarTriggerCint();
extern void G__cpp_setup_globalTriggerCint();
extern void G__cpp_setup_memfuncTriggerCint();
extern void G__cpp_setup_funcTriggerCint();
extern void G__set_cpp_environmentTriggerCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MTriggerIPR.h"
#include "MTriggerCell.h"
#include "MTriggerBit.h"
#include "MTriggerPrescFact.h"
#include "MTriggerLiveTime.h"
#include "MTriggerPattern.h"
#include "MTriggerPatternDecode.h"
#include "MFTriggerPattern.h"
#include "TriggerIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TriggerCintLN_TClass;
extern G__linked_taginfo G__TriggerCintLN_TBuffer;
extern G__linked_taginfo G__TriggerCintLN_TMemberInspector;
extern G__linked_taginfo G__TriggerCintLN_TObject;
extern G__linked_taginfo G__TriggerCintLN_TString;
extern G__linked_taginfo G__TriggerCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TriggerCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TriggerCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TriggerCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TriggerCintLN_MGeomCam;
extern G__linked_taginfo G__TriggerCintLN_MCamEvent;
extern G__linked_taginfo G__TriggerCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TriggerCintLN_MParContainer;
extern G__linked_taginfo G__TriggerCintLN_TArrayL;
extern G__linked_taginfo G__TriggerCintLN_MTriggerIPR;
extern G__linked_taginfo G__TriggerCintLN_TArrayF;
extern G__linked_taginfo G__TriggerCintLN_MTriggerCell;
extern G__linked_taginfo G__TriggerCintLN_MTriggerBit;
extern G__linked_taginfo G__TriggerCintLN_MTriggerPrescFact;
extern G__linked_taginfo G__TriggerCintLN_MTriggerLiveTime;
extern G__linked_taginfo G__TriggerCintLN_MTriggerPattern;
extern G__linked_taginfo G__TriggerCintLN_MTriggerPatternDecode;
extern G__linked_taginfo G__TriggerCintLN_MTriggerPatterncLcLPattern_t;
extern G__linked_taginfo G__TriggerCintLN_MInputStreamID;
extern G__linked_taginfo G__TriggerCintLN_MFilter;
extern G__linked_taginfo G__TriggerCintLN_MParList;
extern G__linked_taginfo G__TriggerCintLN_MTask;
extern G__linked_taginfo G__TriggerCintLN_MRawEvtHeader;
extern G__linked_taginfo G__TriggerCintLN_MRawRunHeader;
extern G__linked_taginfo G__TriggerCintLN_MFTriggerPattern;
extern G__linked_taginfo G__TriggerCintLN_MFTriggerPatterncLcLPrescale_t;

/* STUB derived class for protected member access */
