/********************************************************************
* RanForestCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RanForestCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRanForestCint();
extern void G__cpp_setup_inheritanceRanForestCint();
extern void G__cpp_setup_typetableRanForestCint();
extern void G__cpp_setup_memvarRanForestCint();
extern void G__cpp_setup_globalRanForestCint();
extern void G__cpp_setup_memfuncRanForestCint();
extern void G__cpp_setup_funcRanForestCint();
extern void G__set_cpp_environmentRanForestCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MRanTree.h"
#include "MRanForest.h"
#include "MRanForestGrow.h"
#include "MRanForestCalc.h"
#include "MHRanForest.h"
#include "MHRanForestGini.h"
#include "RanForestIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RanForestCintLN_TClass;
extern G__linked_taginfo G__RanForestCintLN_TBuffer;
extern G__linked_taginfo G__RanForestCintLN_TMemberInspector;
extern G__linked_taginfo G__RanForestCintLN_TObject;
extern G__linked_taginfo G__RanForestCintLN_TString;
extern G__linked_taginfo G__RanForestCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__RanForestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RanForestCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RanForestCintLN_TObjArray;
extern G__linked_taginfo G__RanForestCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RanForestCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RanForestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RanForestCintLN_TEnv;
extern G__linked_taginfo G__RanForestCintLN_TArrayD;
extern G__linked_taginfo G__RanForestCintLN_MParContainer;
extern G__linked_taginfo G__RanForestCintLN_TArrayI;
extern G__linked_taginfo G__RanForestCintLN_TArrayF;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RanForestCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RanForestCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__RanForestCintLN_MArrayI;
extern G__linked_taginfo G__RanForestCintLN_MArrayF;
extern G__linked_taginfo G__RanForestCintLN_MRanTree;
extern G__linked_taginfo G__RanForestCintLN_MDataArray;
extern G__linked_taginfo G__RanForestCintLN_MHMatrix;
extern G__linked_taginfo G__RanForestCintLN_MParList;
extern G__linked_taginfo G__RanForestCintLN_MRanForest;
extern G__linked_taginfo G__RanForestCintLN_MInputStreamID;
extern G__linked_taginfo G__RanForestCintLN_MTask;
extern G__linked_taginfo G__RanForestCintLN_MRead;
extern G__linked_taginfo G__RanForestCintLN_MRanForestGrow;
extern G__linked_taginfo G__RanForestCintLN_MDataPhrase;
extern G__linked_taginfo G__RanForestCintLN_MParameterD;
extern G__linked_taginfo G__RanForestCintLN_MRanForestCalc;
extern G__linked_taginfo G__RanForestCintLN_MRanForestCalccLcLEstimationMode_t;
extern G__linked_taginfo G__RanForestCintLN_MH;
extern G__linked_taginfo G__RanForestCintLN_TGraph;
extern G__linked_taginfo G__RanForestCintLN_MMcEvt;
extern G__linked_taginfo G__RanForestCintLN_MHRanForest;
extern G__linked_taginfo G__RanForestCintLN_TPaveText;
extern G__linked_taginfo G__RanForestCintLN_MHRanForestGini;

/* STUB derived class for protected member access */
