/********************************************************************
* AstroCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AstroCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAstroCint();
extern void G__cpp_setup_inheritanceAstroCint();
extern void G__cpp_setup_typetableAstroCint();
extern void G__cpp_setup_memvarAstroCint();
extern void G__cpp_setup_globalAstroCint();
extern void G__cpp_setup_memfuncAstroCint();
extern void G__cpp_setup_funcAstroCint();
extern void G__set_cpp_environmentAstroCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MVector3.h"
#include "MAstro.h"
#include "MAstroSky2Local.h"
#include "MAstroCatalog.h"
#include "MAstroCamera.h"
#include "MObservatory.h"
#include "AstroIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AstroCintLN_TClass;
extern G__linked_taginfo G__AstroCintLN_TBuffer;
extern G__linked_taginfo G__AstroCintLN_TMemberInspector;
extern G__linked_taginfo G__AstroCintLN_TObject;
extern G__linked_taginfo G__AstroCintLN_TString;
extern G__linked_taginfo G__AstroCintLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__AstroCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__AstroCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AstroCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AstroCintLN_TList;
extern G__linked_taginfo G__AstroCintLN_TClonesArray;
extern G__linked_taginfo G__AstroCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AstroCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AstroCintLN_TVector2;
extern G__linked_taginfo G__AstroCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__AstroCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__AstroCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__AstroCintLN_TRotation;
extern G__linked_taginfo G__AstroCintLN_TVector3;
extern G__linked_taginfo G__AstroCintLN_MVector3;
extern G__linked_taginfo G__AstroCintLN_MVector3cLcLVectorType_t;
extern G__linked_taginfo G__AstroCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AstroCintLN_TArrayD;
extern G__linked_taginfo G__AstroCintLN_MTime;
extern G__linked_taginfo G__AstroCintLN_MAstro;
extern G__linked_taginfo G__AstroCintLN_MObservatory;
extern G__linked_taginfo G__AstroCintLN_MAstroSky2Local;
extern G__linked_taginfo G__AstroCintLN_TAttLine;
extern G__linked_taginfo G__AstroCintLN_TAttMarker;
extern G__linked_taginfo G__AstroCintLN_TGToolTip;
extern G__linked_taginfo G__AstroCintLN_MGMap;
extern G__linked_taginfo G__AstroCintLN_TArrayI;
extern G__linked_taginfo G__AstroCintLN_TGraph;
extern G__linked_taginfo G__AstroCintLN_MAttLine;
extern G__linked_taginfo G__AstroCintLN_MAstroCatalog;
extern G__linked_taginfo G__AstroCintLN_MAstroCatalogcLcLdA;
extern G__linked_taginfo G__AstroCintLN_MGeomCam;
extern G__linked_taginfo G__AstroCintLN_MGeomMirror;
extern G__linked_taginfo G__AstroCintLN_MAstroCamera;
extern G__linked_taginfo G__AstroCintLN_TEnv;
extern G__linked_taginfo G__AstroCintLN_MParContainer;
extern G__linked_taginfo G__AstroCintLN_MObservatorycLcLLocationName_t;

/* STUB derived class for protected member access */
