/********************************************************************
* TrainCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TrainCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTrainCint();
extern void G__cpp_setup_inheritanceTrainCint();
extern void G__cpp_setup_typetableTrainCint();
extern void G__cpp_setup_memvarTrainCint();
extern void G__cpp_setup_globalTrainCint();
extern void G__cpp_setup_memfuncTrainCint();
extern void G__cpp_setup_funcTrainCint();
extern void G__set_cpp_environmentTrainCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MJTrainRanForest.h"
#include "MJTrainEnergy.h"
#include "MJTrainDisp.h"
#include "MJTrainImpact.h"
#include "MJTrainSeparation.h"
#include "MJTrainCuts.h"
#include "TrainIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TrainCintLN_TClass;
extern G__linked_taginfo G__TrainCintLN_TBuffer;
extern G__linked_taginfo G__TrainCintLN_TMemberInspector;
extern G__linked_taginfo G__TrainCintLN_TObject;
extern G__linked_taginfo G__TrainCintLN_TString;
extern G__linked_taginfo G__TrainCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TrainCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TrainCintLN_TList;
extern G__linked_taginfo G__TrainCintLN_TObjArray;
extern G__linked_taginfo G__TrainCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TrainCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TrainCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TrainCintLN_TCanvas;
extern G__linked_taginfo G__TrainCintLN_MParContainer;
extern G__linked_taginfo G__TrainCintLN_MJob;
extern G__linked_taginfo G__TrainCintLN_MTask;
extern G__linked_taginfo G__TrainCintLN_MJOptimizeBase;
extern G__linked_taginfo G__TrainCintLN_MJTrainRanForest;
extern G__linked_taginfo G__TrainCintLN_MDataSet;
extern G__linked_taginfo G__TrainCintLN_MJTrainEnergy;
extern G__linked_taginfo G__TrainCintLN_MH3;
extern G__linked_taginfo G__TrainCintLN_MJTrainDisp;
extern G__linked_taginfo G__TrainCintLN_MJTrainImpact;
extern G__linked_taginfo G__TrainCintLN_MJTrainSeparation;
extern G__linked_taginfo G__TrainCintLN_MJTrainSeparationcLcLType_t;
extern G__linked_taginfo G__TrainCintLN_MBinning;
extern G__linked_taginfo G__TrainCintLN_MJTrainCuts;
extern G__linked_taginfo G__TrainCintLN_MJTrainCutscLcLType_t;

/* STUB derived class for protected member access */
