/********************************************************************
* ToolsCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ToolsCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableToolsCint();
extern void G__cpp_setup_inheritanceToolsCint();
extern void G__cpp_setup_typetableToolsCint();
extern void G__cpp_setup_memvarToolsCint();
extern void G__cpp_setup_globalToolsCint();
extern void G__cpp_setup_memfuncToolsCint();
extern void G__cpp_setup_funcToolsCint();
extern void G__set_cpp_environmentToolsCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MChisqEval.h"
#include "MTFillMatrix.h"
#include "MHSimulatedAnnealing.h"
#include "MSimulatedAnnealing.h"
#include "MFFT.h"
#include "MCubicCoeff.h"
#include "MCubicSpline.h"
#include "MagicReversi.h"
#include "MagicSnake.h"
#include "MagicShow.h"
#include "MagicDomino.h"
#include "MagicCivilization.h"
#include "MineSweeper.h"
#include "MRolke.h"
#include "ToolsIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ToolsCintLN_TClass;
extern G__linked_taginfo G__ToolsCintLN_TBuffer;
extern G__linked_taginfo G__ToolsCintLN_TMemberInspector;
extern G__linked_taginfo G__ToolsCintLN_TObject;
extern G__linked_taginfo G__ToolsCintLN_TString;
extern G__linked_taginfo G__ToolsCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ToolsCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ToolsCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ToolsCintLN_TList;
extern G__linked_taginfo G__ToolsCintLN_TObjArray;
extern G__linked_taginfo G__ToolsCintLN_TTimer;
extern G__linked_taginfo G__ToolsCintLN_TClonesArray;
extern G__linked_taginfo G__ToolsCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ToolsCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ToolsCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ToolsCintLN_TVirtualPad;
extern G__linked_taginfo G__ToolsCintLN_TEnv;
extern G__linked_taginfo G__ToolsCintLN_TArrayD;
extern G__linked_taginfo G__ToolsCintLN_MParContainer;
extern G__linked_taginfo G__ToolsCintLN_MInputStreamID;
extern G__linked_taginfo G__ToolsCintLN_MFilter;
extern G__linked_taginfo G__ToolsCintLN_MParList;
extern G__linked_taginfo G__ToolsCintLN_MTask;
extern G__linked_taginfo G__ToolsCintLN_MData;
extern G__linked_taginfo G__ToolsCintLN_MParameterD;
extern G__linked_taginfo G__ToolsCintLN_MChisqEval;
extern G__linked_taginfo G__ToolsCintLN_MChisqEvalcLcLdA;
extern G__linked_taginfo G__ToolsCintLN_TArrayI;
extern G__linked_taginfo G__ToolsCintLN_TArrayF;
extern G__linked_taginfo G__ToolsCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ToolsCintLN_TH1D;
extern G__linked_taginfo G__ToolsCintLN_TH1;
extern G__linked_taginfo G__ToolsCintLN_TH1I;
extern G__linked_taginfo G__ToolsCintLN_TH1F;
extern G__linked_taginfo G__ToolsCintLN_MArrayF;
extern G__linked_taginfo G__ToolsCintLN_MArrayD;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ToolsCintLN_TH2F;
extern G__linked_taginfo G__ToolsCintLN_MH;
extern G__linked_taginfo G__ToolsCintLN_MH3;
extern G__linked_taginfo G__ToolsCintLN_MRead;
extern G__linked_taginfo G__ToolsCintLN_MHMatrix;
extern G__linked_taginfo G__ToolsCintLN_MTFillMatrix;
extern G__linked_taginfo G__ToolsCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ToolsCintLN_MHSimulatedAnnealing;
extern G__linked_taginfo G__ToolsCintLN_TRandom;
extern G__linked_taginfo G__ToolsCintLN_MSimulatedAnnealing;
extern G__linked_taginfo G__ToolsCintLN_MSimulatedAnnealingcLcLBorderFlag_t;
extern G__linked_taginfo G__ToolsCintLN_MSimulatedAnnealingcLcLVerbosity_t;
extern G__linked_taginfo G__ToolsCintLN_MArrayI;
extern G__linked_taginfo G__ToolsCintLN_MFFT;
extern G__linked_taginfo G__ToolsCintLN_MCubicCoeff;
extern G__linked_taginfo G__ToolsCintLN_MCubicSpline;
extern G__linked_taginfo G__ToolsCintLN_TText;
extern G__linked_taginfo G__ToolsCintLN_TMarker;
extern G__linked_taginfo G__ToolsCintLN_MGeomCam;
extern G__linked_taginfo G__ToolsCintLN_MagicReversi;
extern G__linked_taginfo G__ToolsCintLN_MagicReversicLcLdA;
extern G__linked_taginfo G__ToolsCintLN_MagicSnake;
extern G__linked_taginfo G__ToolsCintLN_MagicSnakecLcLdA;
extern G__linked_taginfo G__ToolsCintLN_MagicShow;
extern G__linked_taginfo G__ToolsCintLN_MagicShowcLcLdA;
extern G__linked_taginfo G__ToolsCintLN_MagicDomino;
extern G__linked_taginfo G__ToolsCintLN_MagicDominocLcLdA;
extern G__linked_taginfo G__ToolsCintLN_MagicCivilization;
extern G__linked_taginfo G__ToolsCintLN_MagicCivilizationcLcLdA;
extern G__linked_taginfo G__ToolsCintLN_MineSweeper;
extern G__linked_taginfo G__ToolsCintLN_MineSweepercLcLdA;
extern G__linked_taginfo G__ToolsCintLN_MRolke;

/* STUB derived class for protected member access */
