/********************************************************************
* CalibCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CalibCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCalibCint();
extern void G__cpp_setup_inheritanceCalibCint();
extern void G__cpp_setup_typetableCalibCint();
extern void G__cpp_setup_memvarCalibCint();
extern void G__cpp_setup_globalCalibCint();
extern void G__cpp_setup_memfuncCalibCint();
extern void G__cpp_setup_funcCalibCint();
extern void G__set_cpp_environmentCalibCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MCalibColorSet.h"
#include "MCalibColorSteer.h"
#include "MCalibCalcFromPast.h"
#include "MCalibrateData.h"
#include "MCalibrateFact.h"
#include "MCalibConstCam.h"
#include "MCalibConstPix.h"
#include "MCalibrationPattern.h"
#include "MCalibrationPatternDecode.h"
#include "MCalibrateRelTimes.h"
#include "MCalibrationCam.h"
#include "MCalibrationPix.h"
#include "MCalibrationPulseTimeCam.h"
#include "MCalibrationRelTimeCam.h"
#include "MCalibrationRelTimePix.h"
#include "MCalibrationRelTimeCalc.h"
#include "MCalibrationQECamMagic.h"
#include "MCalibrationQECam.h"
#include "MCalibrationQEPix.h"
#include "MCalibrationTestCalc.h"
#include "MCalibrationTestCam.h"
#include "MCalibrationTestPix.h"
#include "MCalibrationChargeCalc.h"
#include "MCalibrationChargeCam.h"
#include "MCalibrationChargePix.h"
#include "MCalibrationBlindCam.h"
#include "MCalibrationBlindPix.h"
#include "MCalibrationBlindCamOneOldStyle.h"
#include "MCalibrationBlindCamTwoNewStyle.h"
#include "MCalibrationBlindCamThreeNewStyle.h"
#include "MCalibrationChargePINDiode.h"
#include "CalibIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CalibCintLN_TClass;
extern G__linked_taginfo G__CalibCintLN_TBuffer;
extern G__linked_taginfo G__CalibCintLN_TMemberInspector;
extern G__linked_taginfo G__CalibCintLN_TObject;
extern G__linked_taginfo G__CalibCintLN_TString;
extern G__linked_taginfo G__CalibCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__CalibCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CalibCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibCintLN_TList;
extern G__linked_taginfo G__CalibCintLN_TClonesArray;
extern G__linked_taginfo G__CalibCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CalibCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CalibCintLN_TEnv;
extern G__linked_taginfo G__CalibCintLN_MParContainer;
extern G__linked_taginfo G__CalibCintLN_MInputStreamID;
extern G__linked_taginfo G__CalibCintLN_MParList;
extern G__linked_taginfo G__CalibCintLN_MTask;
extern G__linked_taginfo G__CalibCintLN_MGeomCam;
extern G__linked_taginfo G__CalibCintLN_MCamEvent;
extern G__linked_taginfo G__CalibCintLN_TArrayI;
extern G__linked_taginfo G__CalibCintLN_TArrayF;
extern G__linked_taginfo G__CalibCintLN_TOrdCollection;
extern G__linked_taginfo G__CalibCintLN_MCalibrationPix;
extern G__linked_taginfo G__CalibCintLN_MBadPixelsPix;
extern G__linked_taginfo G__CalibCintLN_MBadPixelsCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationCamcLcLPulserColor_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrationPattern;
extern G__linked_taginfo G__CalibCintLN_MRawEvtHeader;
extern G__linked_taginfo G__CalibCintLN_MCalibColorSet;
extern G__linked_taginfo G__CalibCintLN_MRawRunHeader;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargeCalc;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargeCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationRelTimeCalc;
extern G__linked_taginfo G__CalibCintLN_MCalibrationRelTimeCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationBlindCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationQECam;
extern G__linked_taginfo G__CalibCintLN_MCalibColorSteer;
extern G__linked_taginfo G__CalibCintLN_MCalibrateData;
extern G__linked_taginfo G__CalibCintLN_MCalibCalcFromPast;
extern G__linked_taginfo G__CalibCintLN_MArrayF;
extern G__linked_taginfo G__CalibCintLN_MPedestalCam;
extern G__linked_taginfo G__CalibCintLN_MSignalCam;
extern G__linked_taginfo G__CalibCintLN_MCalibConstCam;
extern G__linked_taginfo G__CalibCintLN_MExtractedSignalCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrateDatacLcLCalibrationMode_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrateDatacLcLPedestalType_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrateDatacLcLSignalType_t;
extern G__linked_taginfo G__CalibCintLN_MArrayD;
extern G__linked_taginfo G__CalibCintLN_MCalibrateFact;
extern G__linked_taginfo G__CalibCintLN_MCalibConstPix;
extern G__linked_taginfo G__CalibCintLN_MCalibrationPatternDecode;
extern G__linked_taginfo G__CalibCintLN_MCalibrationPatterncLcLCLColor_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrationPatternDecodecLcLPulserColorCode_t;
extern G__linked_taginfo G__CalibCintLN_MArrivalTimeCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrateRelTimes;
extern G__linked_taginfo G__CalibCintLN_MCalibrationPixcLcLdA;
extern G__linked_taginfo G__CalibCintLN_MCalibrationPulseTimeCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationRelTimePix;
extern G__linked_taginfo G__CalibCintLN_MBadPixelsPixcLcLUncalibratedType_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrationRelTimeCalccLcLCheck_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrationRelTimeCalccLcLdA;
extern G__linked_taginfo G__CalibCintLN_TArrayC;
extern G__linked_taginfo G__CalibCintLN_TGraphErrors;
extern G__linked_taginfo G__CalibCintLN_TH2D;
extern G__linked_taginfo G__CalibCintLN_MCalibrationQECamcLcLdA;
extern G__linked_taginfo G__CalibCintLN_MCalibrationQECamMagic;
extern G__linked_taginfo G__CalibCintLN_MCalibrationQEPix;
extern G__linked_taginfo G__CalibCintLN_MCalibrationQEPixcLcLdA;
extern G__linked_taginfo G__CalibCintLN_MHCalibrationTestCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationTestCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationTestCalc;
extern G__linked_taginfo G__CalibCintLN_MCalibrationTestPix;
extern G__linked_taginfo G__CalibCintLN_MPedestalPix;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargePINDiode;
extern G__linked_taginfo G__CalibCintLN_MHCalibrationChargeBlindCam;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargePix;
extern G__linked_taginfo G__CalibCintLN_MHCalibrationChargeCam;
extern G__linked_taginfo G__CalibCintLN_MExtractor;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargeCalccLcLCheck_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargeCalccLcLFitResult_t;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargeCalccLcLdA;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargeCamcLcLdA;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargePixcLcLdA;
extern G__linked_taginfo G__CalibCintLN_MCalibrationBlindPix;
extern G__linked_taginfo G__CalibCintLN_MCalibrationBlindPixcLcLdA;
extern G__linked_taginfo G__CalibCintLN_MCalibrationBlindCamOneOldStyle;
extern G__linked_taginfo G__CalibCintLN_MCalibrationBlindCamTwoNewStyle;
extern G__linked_taginfo G__CalibCintLN_MCalibrationBlindCamThreeNewStyle;
extern G__linked_taginfo G__CalibCintLN_MCalibrationChargePINDiodecLcLdA;

/* STUB derived class for protected member access */
