/********************************************************************
* HftCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HftCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHftCint();
extern void G__cpp_setup_inheritanceHftCint();
extern void G__cpp_setup_typetableHftCint();
extern void G__cpp_setup_memvarHftCint();
extern void G__cpp_setup_globalHftCint();
extern void G__cpp_setup_memfuncHftCint();
extern void G__cpp_setup_funcHftCint();
extern void G__set_cpp_environmentHftCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MHexagonalFT.h"
#include "MHexagonalFTCalc.h"
#include "MHexagonFreqSpace.h"
#include "MGeomCamMagicXT.h"
#include "MGeomCamMagicEnhance.h"
#include "HftIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HftCintLN_TClass;
extern G__linked_taginfo G__HftCintLN_TBuffer;
extern G__linked_taginfo G__HftCintLN_TMemberInspector;
extern G__linked_taginfo G__HftCintLN_TObject;
extern G__linked_taginfo G__HftCintLN_TString;
extern G__linked_taginfo G__HftCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HftCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HftCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HftCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HftCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HftCintLN_MArrayF;
extern G__linked_taginfo G__HftCintLN_MArrayI;
extern G__linked_taginfo G__HftCintLN_MArrayD;
extern G__linked_taginfo G__HftCintLN_MGeomCam;
extern G__linked_taginfo G__HftCintLN_MHexagonalFT;
extern G__linked_taginfo G__HftCintLN_MParContainer;
extern G__linked_taginfo G__HftCintLN_MInputStreamID;
extern G__linked_taginfo G__HftCintLN_MParList;
extern G__linked_taginfo G__HftCintLN_MTask;
extern G__linked_taginfo G__HftCintLN_MSignalCam;
extern G__linked_taginfo G__HftCintLN_MHexagonFreqSpace;
extern G__linked_taginfo G__HftCintLN_MHexagonalFTCalc;
extern G__linked_taginfo G__HftCintLN_MCamEvent;
extern G__linked_taginfo G__HftCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HftCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HftCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__HftCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__HftCintLN_MGeomCamDwarf;
extern G__linked_taginfo G__HftCintLN_MGeomCamMagicXT;
extern G__linked_taginfo G__HftCintLN_MGeomCamMagicEnhance;

/* STUB derived class for protected member access */
