/********************************************************************
* SimReflectorCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SimReflectorCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimReflectorCint();
extern void G__cpp_setup_inheritanceSimReflectorCint();
extern void G__cpp_setup_typetableSimReflectorCint();
extern void G__cpp_setup_memvarSimReflectorCint();
extern void G__cpp_setup_globalSimReflectorCint();
extern void G__cpp_setup_memfuncSimReflectorCint();
extern void G__cpp_setup_funcSimReflectorCint();
extern void G__set_cpp_environmentSimReflectorCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MSimReflector.h"
#include "MSimRays.h"
#include "MReflector.h"
#include "MMirror.h"
#include "MMirrorSquare.h"
#include "MMirrorHex.h"
#include "MMirrorDisk.h"
#include "SimReflectorIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimReflectorCintLN_TClass;
extern G__linked_taginfo G__SimReflectorCintLN_TBuffer;
extern G__linked_taginfo G__SimReflectorCintLN_TMemberInspector;
extern G__linked_taginfo G__SimReflectorCintLN_TObject;
extern G__linked_taginfo G__SimReflectorCintLN_TString;
extern G__linked_taginfo G__SimReflectorCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SimReflectorCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimReflectorCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimReflectorCintLN_TObjArray;
extern G__linked_taginfo G__SimReflectorCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimReflectorCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimReflectorCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SimReflectorCintLN_TEnv;
extern G__linked_taginfo G__SimReflectorCintLN_MParContainer;
extern G__linked_taginfo G__SimReflectorCintLN_MInputStreamID;
extern G__linked_taginfo G__SimReflectorCintLN_MParList;
extern G__linked_taginfo G__SimReflectorCintLN_MTask;
extern G__linked_taginfo G__SimReflectorCintLN_MGeomCam;
extern G__linked_taginfo G__SimReflectorCintLN_MPointingPos;
extern G__linked_taginfo G__SimReflectorCintLN_MPhotonEvent;
extern G__linked_taginfo G__SimReflectorCintLN_MCorsikaEvtHeader;
extern G__linked_taginfo G__SimReflectorCintLN_MReflector;
extern G__linked_taginfo G__SimReflectorCintLN_MSimReflector;
extern G__linked_taginfo G__SimReflectorCintLN_MSimRays;
extern G__linked_taginfo G__SimReflectorCintLN_MQuaternion;
extern G__linked_taginfo G__SimReflectorCintLN_MMirror;
extern G__linked_taginfo G__SimReflectorCintLN_TVector2;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SimReflectorCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SimReflectorCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__SimReflectorCintLN_TRotation;
extern G__linked_taginfo G__SimReflectorCintLN_TVector3;
extern G__linked_taginfo G__SimReflectorCintLN_MMirrorSquare;
extern G__linked_taginfo G__SimReflectorCintLN_MMirrorHex;
extern G__linked_taginfo G__SimReflectorCintLN_MMirrorHex90;
extern G__linked_taginfo G__SimReflectorCintLN_MMirrorHex15;
extern G__linked_taginfo G__SimReflectorCintLN_MMirrorDisk;

/* STUB derived class for protected member access */
