/********************************************************************
* SimCameraCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SimCameraCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimCameraCint();
extern void G__cpp_setup_inheritanceSimCameraCint();
extern void G__cpp_setup_typetableSimCameraCint();
extern void G__cpp_setup_memvarSimCameraCint();
extern void G__cpp_setup_globalSimCameraCint();
extern void G__cpp_setup_memfuncSimCameraCint();
extern void G__cpp_setup_funcSimCameraCint();
extern void G__set_cpp_environmentSimCameraCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MSimPSF.h"
#include "MSimGeomCam.h"
#include "MSimRandomPhotons.h"
#include "MSimAPD.h"
#include "MSimBundlePhotons.h"
#include "MSimCalibrationSignal.h"
#include "MSimExcessNoise.h"
#include "MSimCamera.h"
#include "MSimTrigger.h"
#include "MSimReadout.h"
#include "MSimSignalCam.h"
#include "MTruePhotonsPerPixelCont.h"
#include "SimCameraIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimCameraCintLN_TClass;
extern G__linked_taginfo G__SimCameraCintLN_TBuffer;
extern G__linked_taginfo G__SimCameraCintLN_TMemberInspector;
extern G__linked_taginfo G__SimCameraCintLN_TObject;
extern G__linked_taginfo G__SimCameraCintLN_TString;
extern G__linked_taginfo G__SimCameraCintLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SimCameraCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimCameraCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCameraCintLN_TObjArray;
extern G__linked_taginfo G__SimCameraCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimCameraCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCameraCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SimCameraCintLN_TEnv;
extern G__linked_taginfo G__SimCameraCintLN_MParContainer;
extern G__linked_taginfo G__SimCameraCintLN_MInputStreamID;
extern G__linked_taginfo G__SimCameraCintLN_MParList;
extern G__linked_taginfo G__SimCameraCintLN_MTask;
extern G__linked_taginfo G__SimCameraCintLN_MPhotonEvent;
extern G__linked_taginfo G__SimCameraCintLN_MSimPSF;
extern G__linked_taginfo G__SimCameraCintLN_MGeomCam;
extern G__linked_taginfo G__SimCameraCintLN_MPhotonStatistics;
extern G__linked_taginfo G__SimCameraCintLN_MSignalCam;
extern G__linked_taginfo G__SimCameraCintLN_MParameterD;
extern G__linked_taginfo G__SimCameraCintLN_MRawRunHeader;
extern G__linked_taginfo G__SimCameraCintLN_MParSpline;
extern G__linked_taginfo G__SimCameraCintLN_MSimGeomCam;
extern G__linked_taginfo G__SimCameraCintLN_MCorsikaRunHeader;
extern G__linked_taginfo G__SimCameraCintLN_MPedestalCam;
extern G__linked_taginfo G__SimCameraCintLN_MSimRandomPhotons;
extern G__linked_taginfo G__SimCameraCintLN_MSimAPD;
extern G__linked_taginfo G__SimCameraCintLN_MArrayI;
extern G__linked_taginfo G__SimCameraCintLN_MLut;
extern G__linked_taginfo G__SimCameraCintLN_MSimBundlePhotons;
extern G__linked_taginfo G__SimCameraCintLN_MRead;
extern G__linked_taginfo G__SimCameraCintLN_MRawEvtHeader;
extern G__linked_taginfo G__SimCameraCintLN_MSimCalibrationSignal;
extern G__linked_taginfo G__SimCameraCintLN_MSimExcessNoise;
extern G__linked_taginfo G__SimCameraCintLN_MArrayF;
extern G__linked_taginfo G__SimCameraCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__SimCameraCintLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCameraCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__SimCameraCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCameraCintLN_MMatrix;
extern G__linked_taginfo G__SimCameraCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__SimCameraCintLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCameraCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__SimCameraCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimCameraCintLN_MMcEvt;
extern G__linked_taginfo G__SimCameraCintLN_MAnalogChannels;
extern G__linked_taginfo G__SimCameraCintLN_MTruePhotonsPerPixelCont;
extern G__linked_taginfo G__SimCameraCintLN_MSpline3;
extern G__linked_taginfo G__SimCameraCintLN_MSimCamera;
extern G__linked_taginfo G__SimCameraCintLN_MSimTrigger;
extern G__linked_taginfo G__SimCameraCintLN_MRawEvtData;
extern G__linked_taginfo G__SimCameraCintLN_MSimReadout;
extern G__linked_taginfo G__SimCameraCintLN_MArrayD;
extern G__linked_taginfo G__SimCameraCintLN_MSimSignalCam;

/* STUB derived class for protected member access */
