/********************************************************************
* CameraCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CameraCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCameraCint();
extern void G__cpp_setup_inheritanceCameraCint();
extern void G__cpp_setup_typetableCameraCint();
extern void G__cpp_setup_memvarCameraCint();
extern void G__cpp_setup_globalCameraCint();
extern void G__cpp_setup_memfuncCameraCint();
extern void G__cpp_setup_funcCameraCint();
extern void G__set_cpp_environmentCameraCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MCameraAUX.h"
#include "MCameraCalibration.h"
#include "MCameraCooling.h"
#include "MCameraHV.h"
#include "MCameraLV.h"
#include "MCameraTH.h"
#include "MCameraTD.h"
#include "MCameraRecTemp.h"
#include "MCameraDC.h"
#include "MCameraLid.h"
#include "MCameraLids.h"
#include "MCameraActiveLoad.h"
#include "MCameraCentralPix.h"
#include "MCameraPowerSupply.h"
#include "CameraIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CameraCintLN_TClass;
extern G__linked_taginfo G__CameraCintLN_TBuffer;
extern G__linked_taginfo G__CameraCintLN_TMemberInspector;
extern G__linked_taginfo G__CameraCintLN_TObject;
extern G__linked_taginfo G__CameraCintLN_TString;
extern G__linked_taginfo G__CameraCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CameraCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CameraCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CameraCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CameraCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CameraCintLN_MParContainer;
extern G__linked_taginfo G__CameraCintLN_MCameraAUX;
extern G__linked_taginfo G__CameraCintLN_MCameraCalibration;
extern G__linked_taginfo G__CameraCintLN_MCameraCooling;
extern G__linked_taginfo G__CameraCintLN_MGeomCam;
extern G__linked_taginfo G__CameraCintLN_MCamEvent;
extern G__linked_taginfo G__CameraCintLN_TArrayS;
extern G__linked_taginfo G__CameraCintLN_MCameraHV;
extern G__linked_taginfo G__CameraCintLN_MCameraPowerSupply;
extern G__linked_taginfo G__CameraCintLN_MCameraLV;
extern G__linked_taginfo G__CameraCintLN_TArrayC;
extern G__linked_taginfo G__CameraCintLN_MCameraTD;
extern G__linked_taginfo G__CameraCintLN_MCameraTH;
extern G__linked_taginfo G__CameraCintLN_TArrayF;
extern G__linked_taginfo G__CameraCintLN_MCameraRecTemp;
extern G__linked_taginfo G__CameraCintLN_MCameraDC;
extern G__linked_taginfo G__CameraCintLN_MCameraLid;
extern G__linked_taginfo G__CameraCintLN_MCameraLids;
extern G__linked_taginfo G__CameraCintLN_MCameraActiveLoad;
extern G__linked_taginfo G__CameraCintLN_MCameraCentralPix;

/* STUB derived class for protected member access */
