/********************************************************************
* BadPixelsCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BadPixelsCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBadPixelsCint();
extern void G__cpp_setup_inheritanceBadPixelsCint();
extern void G__cpp_setup_typetableBadPixelsCint();
extern void G__cpp_setup_memvarBadPixelsCint();
extern void G__cpp_setup_globalBadPixelsCint();
extern void G__cpp_setup_memfuncBadPixelsCint();
extern void G__cpp_setup_funcBadPixelsCint();
extern void G__set_cpp_environmentBadPixelsCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MBadPixelsPix.h"
#include "MBadPixelsCam.h"
#include "MBadPixelsMerge.h"
#include "MBadPixelsCalc.h"
#include "MBadPixelsTreat.h"
#include "MMcBadPixelsSet.h"
#include "MHBadPixels.h"
#include "BadPixelsIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BadPixelsCintLN_TClass;
extern G__linked_taginfo G__BadPixelsCintLN_TBuffer;
extern G__linked_taginfo G__BadPixelsCintLN_TMemberInspector;
extern G__linked_taginfo G__BadPixelsCintLN_TObject;
extern G__linked_taginfo G__BadPixelsCintLN_TString;
extern G__linked_taginfo G__BadPixelsCintLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BadPixelsCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BadPixelsCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BadPixelsCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BadPixelsCintLN_TList;
extern G__linked_taginfo G__BadPixelsCintLN_TObjArray;
extern G__linked_taginfo G__BadPixelsCintLN_TClonesArray;
extern G__linked_taginfo G__BadPixelsCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BadPixelsCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BadPixelsCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BadPixelsCintLN_TEnv;
extern G__linked_taginfo G__BadPixelsCintLN_MParContainer;
extern G__linked_taginfo G__BadPixelsCintLN_TArrayI;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsPix;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsPixcLcLUnsuitableType_t;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsPixcLcLUncalibratedType_t;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsPixcLcLHardwareType_t;
extern G__linked_taginfo G__BadPixelsCintLN_MGeomCam;
extern G__linked_taginfo G__BadPixelsCintLN_MCamEvent;
extern G__linked_taginfo G__BadPixelsCintLN_TArrayC;
extern G__linked_taginfo G__BadPixelsCintLN_MGeom;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsCam;
extern G__linked_taginfo G__BadPixelsCintLN_MInputStreamID;
extern G__linked_taginfo G__BadPixelsCintLN_MParList;
extern G__linked_taginfo G__BadPixelsCintLN_MTask;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsMerge;
extern G__linked_taginfo G__BadPixelsCintLN_MPedPhotCam;
extern G__linked_taginfo G__BadPixelsCintLN_MPedestalCam;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsCalc;
extern G__linked_taginfo G__BadPixelsCintLN_MSignalCam;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsTreat;
extern G__linked_taginfo G__BadPixelsCintLN_MBadPixelsTreatcLcLdA;
extern G__linked_taginfo G__BadPixelsCintLN_MMcBadPixelsSet;
extern G__linked_taginfo G__BadPixelsCintLN_TH2;
extern G__linked_taginfo G__BadPixelsCintLN_MBinning;
extern G__linked_taginfo G__BadPixelsCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BadPixelsCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BadPixelsCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BadPixelsCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BadPixelsCintLN_TH2D;
extern G__linked_taginfo G__BadPixelsCintLN_MH;
extern G__linked_taginfo G__BadPixelsCintLN_MPointingPos;
extern G__linked_taginfo G__BadPixelsCintLN_MHBadPixels;

/* STUB derived class for protected member access */
