/********************************************************************
* GuiCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GuiCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGuiCint();
extern void G__cpp_setup_inheritanceGuiCint();
extern void G__cpp_setup_typetableGuiCint();
extern void G__cpp_setup_memvarGuiCint();
extern void G__cpp_setup_globalGuiCint();
extern void G__cpp_setup_memfuncGuiCint();
extern void G__cpp_setup_funcGuiCint();
extern void G__set_cpp_environmentGuiCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MHexagon.h"
#include "MCamEvent.h"
#include "GuiIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GuiCintLN_TClass;
extern G__linked_taginfo G__GuiCintLN_TBuffer;
extern G__linked_taginfo G__GuiCintLN_TMemberInspector;
extern G__linked_taginfo G__GuiCintLN_TObject;
extern G__linked_taginfo G__GuiCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__GuiCintLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__GuiCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GuiCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GuiCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GuiCintLN_TAttLine;
extern G__linked_taginfo G__GuiCintLN_TAttFill;
extern G__linked_taginfo G__GuiCintLN_MHexagon;
extern G__linked_taginfo G__GuiCintLN_TArrayD;
extern G__linked_taginfo G__GuiCintLN_MGeomCam;
extern G__linked_taginfo G__GuiCintLN_MCamEvent;

/* STUB derived class for protected member access */
