/********************************************************************
* GeomCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GeomCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGeomCint();
extern void G__cpp_setup_inheritanceGeomCint();
extern void G__cpp_setup_typetableGeomCint();
extern void G__cpp_setup_memvarGeomCint();
extern void G__cpp_setup_globalGeomCint();
extern void G__cpp_setup_memfuncGeomCint();
extern void G__cpp_setup_funcGeomCint();
extern void G__set_cpp_environmentGeomCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MGeom.h"
#include "MGeomPix.h"
#include "MGeomRectangle.h"
#include "MGeomCam.h"
#include "MGeomCamCT1.h"
#include "MGeomCamDwarf.h"
#include "MGeomCamFact.h"
#include "MGeomCamFACT.h"
#include "MGeomCamMagic.h"
#include "MGeomCamSquare.h"
#include "MGeomCorsikaCT.h"
#include "MGeomMirror.h"
#include "MGeomPMT.h"
#include "GeomIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GeomCintLN_TClass;
extern G__linked_taginfo G__GeomCintLN_TBuffer;
extern G__linked_taginfo G__GeomCintLN_TMemberInspector;
extern G__linked_taginfo G__GeomCintLN_TObject;
extern G__linked_taginfo G__GeomCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GeomCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GeomCintLN_TList;
extern G__linked_taginfo G__GeomCintLN_TObjArray;
extern G__linked_taginfo G__GeomCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GeomCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GeomCintLN_MGeomCam;
extern G__linked_taginfo G__GeomCintLN_TAttLine;
extern G__linked_taginfo G__GeomCintLN_TAttFill;
extern G__linked_taginfo G__GeomCintLN_TVector2;
extern G__linked_taginfo G__GeomCintLN_MGeom;
extern G__linked_taginfo G__GeomCintLN_MGeomcLcLdA;
extern G__linked_taginfo G__GeomCintLN_MGeomPix;
extern G__linked_taginfo G__GeomCintLN_MGeomPixcLcLdA;
extern G__linked_taginfo G__GeomCintLN_MGeomRectangle;
extern G__linked_taginfo G__GeomCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GeomCintLN_MParContainer;
extern G__linked_taginfo G__GeomCintLN_TArrayF;
extern G__linked_taginfo G__GeomCintLN_TArrayS;
extern G__linked_taginfo G__GeomCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GeomCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GeomCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GeomCintLN_TRotation;
extern G__linked_taginfo G__GeomCintLN_TVector3;
extern G__linked_taginfo G__GeomCintLN_MQuaternion;
extern G__linked_taginfo G__GeomCintLN_TArrayI;
extern G__linked_taginfo G__GeomCintLN_MGeomCamDwarf;
extern G__linked_taginfo G__GeomCintLN_MGeomCamCT1;
extern G__linked_taginfo G__GeomCintLN_MGeomCamFact;
extern G__linked_taginfo G__GeomCintLN_MGeomCamFACT;
extern G__linked_taginfo G__GeomCintLN_MGeomCamFACTcLcLdA;
extern G__linked_taginfo G__GeomCintLN_MGeomCamMagic;
extern G__linked_taginfo G__GeomCintLN_MGeomCamMagicII;
extern G__linked_taginfo G__GeomCintLN_MGeomCamSquare;
extern G__linked_taginfo G__GeomCintLN_MGeomCorsikaCT;
extern G__linked_taginfo G__GeomCintLN_MGeomMirror;
extern G__linked_taginfo G__GeomCintLN_MGeomPMT;

/* STUB derived class for protected member access */
