/********************************************************************
* HistCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HistCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHistCint();
extern void G__cpp_setup_inheritanceHistCint();
extern void G__cpp_setup_typetableHistCint();
extern void G__cpp_setup_memvarHistCint();
extern void G__cpp_setup_globalHistCint();
extern void G__cpp_setup_memfuncHistCint();
extern void G__cpp_setup_funcHistCint();
extern void G__set_cpp_environmentHistCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MHEvent.h"
#include "MHCamEvent.h"
#include "MHCamEventRot.h"
#include "MHStarMap.h"
#include "MHHadronness.h"
#include "MHTriggerLvl0.h"
#include "MHCamera.h"
#include "MHRate.h"
#include "MHWeather.h"
#include "HistIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HistCintLN_TClass;
extern G__linked_taginfo G__HistCintLN_TBuffer;
extern G__linked_taginfo G__HistCintLN_TMemberInspector;
extern G__linked_taginfo G__HistCintLN_TObject;
extern G__linked_taginfo G__HistCintLN_TNamed;
extern G__linked_taginfo G__HistCintLN_TString;
extern G__linked_taginfo G__HistCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__HistCintLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__HistCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HistCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistCintLN_TList;
extern G__linked_taginfo G__HistCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HistCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HistCintLN_TCanvas;
extern G__linked_taginfo G__HistCintLN_TArrayD;
extern G__linked_taginfo G__HistCintLN_MParContainer;
extern G__linked_taginfo G__HistCintLN_TH1;
extern G__linked_taginfo G__HistCintLN_TH1D;
extern G__linked_taginfo G__HistCintLN_TArrayF;
extern G__linked_taginfo G__HistCintLN_MArrayD;
extern G__linked_taginfo G__HistCintLN_TProfile;
extern G__linked_taginfo G__HistCintLN_MParList;
extern G__linked_taginfo G__HistCintLN_TArray;
extern G__linked_taginfo G__HistCintLN_TAttLine;
extern G__linked_taginfo G__HistCintLN_TAttFill;
extern G__linked_taginfo G__HistCintLN_TAttMarker;
extern G__linked_taginfo G__HistCintLN_TArrayC;
extern G__linked_taginfo G__HistCintLN_TArrayI;
extern G__linked_taginfo G__HistCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HistCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HistCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HistCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HistCintLN_TH2F;
extern G__linked_taginfo G__HistCintLN_TH2D;
extern G__linked_taginfo G__HistCintLN_MH;
extern G__linked_taginfo G__HistCintLN_MHCamera;
extern G__linked_taginfo G__HistCintLN_MRawEvtData;
extern G__linked_taginfo G__HistCintLN_MRawRunHeader;
extern G__linked_taginfo G__HistCintLN_MRawEvtHeader;
extern G__linked_taginfo G__HistCintLN_MTime;
extern G__linked_taginfo G__HistCintLN_MMcEvt;
extern G__linked_taginfo G__HistCintLN_MMcTrig;
extern G__linked_taginfo G__HistCintLN_MSignalCam;
extern G__linked_taginfo G__HistCintLN_MImgCleanStd;
extern G__linked_taginfo G__HistCintLN_MTriggerPattern;
extern G__linked_taginfo G__HistCintLN_MHEvent;
extern G__linked_taginfo G__HistCintLN_MHEventcLcLEventType_t;
extern G__linked_taginfo G__HistCintLN_MCamEvent;
extern G__linked_taginfo G__HistCintLN_MHCamEvent;
extern G__linked_taginfo G__HistCintLN_MHCamEventcLcLdA;
extern G__linked_taginfo G__HistCintLN_MGeomCam;
extern G__linked_taginfo G__HistCintLN_MPointingPos;
extern G__linked_taginfo G__HistCintLN_MObservatory;
extern G__linked_taginfo G__HistCintLN_MHCamEventRot;
extern G__linked_taginfo G__HistCintLN_MHCamEventRotcLcLdA;
extern G__linked_taginfo G__HistCintLN_MSrcPosCam;
extern G__linked_taginfo G__HistCintLN_MHStarMap;
extern G__linked_taginfo G__HistCintLN_TGraph;
extern G__linked_taginfo G__HistCintLN_MParameterD;
extern G__linked_taginfo G__HistCintLN_MHMatrix;
extern G__linked_taginfo G__HistCintLN_MHHadronness;
extern G__linked_taginfo G__HistCintLN_MHTriggerLvl0;
extern G__linked_taginfo G__HistCintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__HistCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__HistCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistCintLN_TPaveStats;
extern G__linked_taginfo G__HistCintLN_MHCameracLcLdA;
extern G__linked_taginfo G__HistCintLN_MEventRate;
extern G__linked_taginfo G__HistCintLN_MHRate;
extern G__linked_taginfo G__HistCintLN_MReportCC;
extern G__linked_taginfo G__HistCintLN_MReportPyrometer;
extern G__linked_taginfo G__HistCintLN_MHWeather;

/* STUB derived class for protected member access */
