/********************************************************************
* BaseCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BaseCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBaseCint();
extern void G__cpp_setup_inheritanceBaseCint();
extern void G__cpp_setup_typetableBaseCint();
extern void G__cpp_setup_memvarBaseCint();
extern void G__cpp_setup_globalBaseCint();
extern void G__cpp_setup_memfuncBaseCint();
extern void G__cpp_setup_funcBaseCint();
extern void G__set_cpp_environmentBaseCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MAGIC.h"
#include "MLogo.h"
#include "MArgs.h"
#include "MString.h"
#include "MMath.h"
#include "MSpline3.h"
#include "MReflection.h"
#include "MQuaternion.h"
#include "MEnv.h"
#include "MLog.h"
#include "MLogManip.h"
#include "MLogPlugin.h"
#include "MLogHtml.h"
#include "MParSpline.h"
#include "MParList.h"
#include "MParContainer.h"
#include "MParEmulated.h"
#include "MParEnv.h"
#include "MParameters.h"
#include "MInputStreamID.h"
#include "MTask.h"
#include "MTaskEnv.h"
#include "MTaskInteractive.h"
#include "MTaskList.h"
#include "MFilter.h"
#include "MEvtLoop.h"
#include "MProgressBar.h"
#include "MSearch.h"
#include "MIter.h"
#include "MDirIter.h"
#include "MReadSocket.h"
#include "MGGroupFrame.h"
#include "MGMenu.h"
#include "MGMap.h"
#include "MGList.h"
#include "MGTask.h"
#include "MStatusArray.h"
#include "MStatusDisplay.h"
#include "MLut.h"
#include "MArray.h"
#include "MArrayB.h"
#include "MArrayS.h"
#include "MArrayD.h"
#include "MArrayF.h"
#include "MArrayI.h"
#include "MTime.h"
#include "MClone.h"
#include "MContinue.h"
#include "MPrint.h"
#include "MThread.h"
#include "MObjLookup.h"
#include "BaseIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BaseCintLN_TClass;
extern G__linked_taginfo G__BaseCintLN_TBuffer;
extern G__linked_taginfo G__BaseCintLN_TMemberInspector;
extern G__linked_taginfo G__BaseCintLN_TObject;
extern G__linked_taginfo G__BaseCintLN_TNamed;
extern G__linked_taginfo G__BaseCintLN_TCollection;
extern G__linked_taginfo G__BaseCintLN_TString;
extern G__linked_taginfo G__BaseCintLN_TVirtualCollectionProxy;
extern G__linked_taginfo G__BaseCintLN_ios_base;
extern G__linked_taginfo G__BaseCintLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BaseCintLN_basic_ioslEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BaseCintLN_basic_streambuflEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BaseCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BaseCintLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseCintLN_va_list;
extern G__linked_taginfo G__BaseCintLN_TList;
extern G__linked_taginfo G__BaseCintLN_TObjArray;
extern G__linked_taginfo G__BaseCintLN_TTimer;
extern G__linked_taginfo G__BaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseCintLN_TPRegexp;
extern G__linked_taginfo G__BaseCintLN_TIterator;
extern G__linked_taginfo G__BaseCintLN_TIter;
extern G__linked_taginfo G__BaseCintLN_TSeqCollection;
extern G__linked_taginfo G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BaseCintLN_TDatime;
extern G__linked_taginfo G__BaseCintLN_TCanvas;
extern G__linked_taginfo G__BaseCintLN_TVirtualPad;
extern G__linked_taginfo G__BaseCintLN_MARS;
extern G__linked_taginfo G__BaseCintLN_UTF8;
extern G__linked_taginfo G__BaseCintLN_MArgsEntry;
extern G__linked_taginfo G__BaseCintLN_MArgs;
extern G__linked_taginfo G__BaseCintLN_MString;
extern G__linked_taginfo G__BaseCintLN_TVector2;
extern G__linked_taginfo G__BaseCintLN_TVector3;
extern G__linked_taginfo G__BaseCintLN_TArrayD;
extern G__linked_taginfo G__BaseCintLN_MMath;
extern G__linked_taginfo G__BaseCintLN_TAttLine;
extern G__linked_taginfo G__BaseCintLN_TAttFill;
extern G__linked_taginfo G__BaseCintLN_TAttMarker;
extern G__linked_taginfo G__BaseCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BaseCintLN_TH1;
extern G__linked_taginfo G__BaseCintLN_TF1;
extern G__linked_taginfo G__BaseCintLN_TSpline;
extern G__linked_taginfo G__BaseCintLN_TGraph;
extern G__linked_taginfo G__BaseCintLN_TSpline3;
extern G__linked_taginfo G__BaseCintLN_MArrayD;
extern G__linked_taginfo G__BaseCintLN_MSpline3;
extern G__linked_taginfo G__BaseCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BaseCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BaseCintLN_TRotation;
extern G__linked_taginfo G__BaseCintLN_TQuaternion;
extern G__linked_taginfo G__BaseCintLN_MReflection;
extern G__linked_taginfo G__BaseCintLN_MQuaternion;
extern G__linked_taginfo G__BaseCintLN_TEnv;
extern G__linked_taginfo G__BaseCintLN_EEnvLevel;
extern G__linked_taginfo G__BaseCintLN_TOrdCollection;
extern G__linked_taginfo G__BaseCintLN_TAttText;
extern G__linked_taginfo G__BaseCintLN_TPave;
extern G__linked_taginfo G__BaseCintLN_MEnv;
extern G__linked_taginfo G__BaseCintLN_TSocket;
extern G__linked_taginfo G__BaseCintLN_TServerSocket;
extern G__linked_taginfo G__BaseCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__BaseCintLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__BaseCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseCintLN_TQObject;
extern G__linked_taginfo G__BaseCintLN_TTime;
extern G__linked_taginfo G__BaseCintLN_TMutex;
extern G__linked_taginfo G__BaseCintLN_TGTextView;
extern G__linked_taginfo G__BaseCintLN_MLogPlugin;
extern G__linked_taginfo G__BaseCintLN_MLog;
extern G__linked_taginfo G__BaseCintLN_MLogcLcL_flags;
extern G__linked_taginfo G__BaseCintLN_MLogcLcLELogBits;
extern G__linked_taginfo G__BaseCintLN_MLogcLcLELogType;
extern G__linked_taginfo G__BaseCintLN_MLogcLcLdA;
extern G__linked_taginfo G__BaseCintLN_MLogHtml;
extern G__linked_taginfo G__BaseCintLN_MLogHtmlcLcLdA;
extern G__linked_taginfo G__BaseCintLN_fits;
extern G__linked_taginfo G__BaseCintLN_TDataMember;
extern G__linked_taginfo G__BaseCintLN_TMethodCall;
extern G__linked_taginfo G__BaseCintLN_MStatusDisplay;
extern G__linked_taginfo G__BaseCintLN_MParContainer;
extern G__linked_taginfo G__BaseCintLN_MParEmulated;
extern G__linked_taginfo G__BaseCintLN_MParContainercLcLdA;
extern G__linked_taginfo G__BaseCintLN_MParSpline;
extern G__linked_taginfo G__BaseCintLN_MTask;
extern G__linked_taginfo G__BaseCintLN_MTaskList;
extern G__linked_taginfo G__BaseCintLN_MParList;
extern G__linked_taginfo G__BaseCintLN_MParListcLcLdA;
extern G__linked_taginfo G__BaseCintLN_MParEnv;
extern G__linked_taginfo G__BaseCintLN_MParameterD;
extern G__linked_taginfo G__BaseCintLN_MParameterDerr;
extern G__linked_taginfo G__BaseCintLN_MParameterI;
extern G__linked_taginfo G__BaseCintLN_MInputStreamID;
extern G__linked_taginfo G__BaseCintLN_TStopwatch;
extern G__linked_taginfo G__BaseCintLN_MFilter;
extern G__linked_taginfo G__BaseCintLN_MTaskcLcLdA;
extern G__linked_taginfo G__BaseCintLN_MTaskEnv;
extern G__linked_taginfo G__BaseCintLN_MTaskEnvcLcLdA;
extern G__linked_taginfo G__BaseCintLN_MTaskInteractive;
extern G__linked_taginfo G__BaseCintLN_MTaskListcLcLdA;
extern G__linked_taginfo G__BaseCintLN_TGProgressBar;
extern G__linked_taginfo G__BaseCintLN_MProgressBar;
extern G__linked_taginfo G__BaseCintLN_MEvtLoop;
extern G__linked_taginfo G__BaseCintLN_MEvtLoopcLcLdA;
extern G__linked_taginfo G__BaseCintLN_MEvtLoopcLcLStatistics_t;
extern G__linked_taginfo G__BaseCintLN_Event_t;
extern G__linked_taginfo G__BaseCintLN_TGObject;
extern G__linked_taginfo G__BaseCintLN_TGWindow;
extern G__linked_taginfo G__BaseCintLN_TGPicture;
extern G__linked_taginfo G__BaseCintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__BaseCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__BaseCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseCintLN_TGFrame;
extern G__linked_taginfo G__BaseCintLN_TGCompositeFrame;
extern G__linked_taginfo G__BaseCintLN_TGLayoutHints;
extern G__linked_taginfo G__BaseCintLN_TGString;
extern G__linked_taginfo G__BaseCintLN_TGMainFrame;
extern G__linked_taginfo G__BaseCintLN_TGTransientFrame;
extern G__linked_taginfo G__BaseCintLN_TGGroupFrame;
extern G__linked_taginfo G__BaseCintLN_MGList;
extern G__linked_taginfo G__BaseCintLN_TGHProgressBar;
extern G__linked_taginfo G__BaseCintLN_TGWidget;
extern G__linked_taginfo G__BaseCintLN_MSearch;
extern G__linked_taginfo G__BaseCintLN_MIter;
extern G__linked_taginfo G__BaseCintLN_MDirIter;
extern G__linked_taginfo G__BaseCintLN_MReadSocket;
extern G__linked_taginfo G__BaseCintLN_MGTask;
extern G__linked_taginfo G__BaseCintLN_MGGroupFrame;
extern G__linked_taginfo G__BaseCintLN_TGPopupMenu;
extern G__linked_taginfo G__BaseCintLN_MGMenuBar;
extern G__linked_taginfo G__BaseCintLN_TExMap;
extern G__linked_taginfo G__BaseCintLN_MGMap;
extern G__linked_taginfo G__BaseCintLN_MGMapcLcLdA;
extern G__linked_taginfo G__BaseCintLN_MStatusArray;
extern G__linked_taginfo G__BaseCintLN_MStatusArraycLcLdA;
extern G__linked_taginfo G__BaseCintLN_TImage;
extern G__linked_taginfo G__BaseCintLN_TImagecLcLEImageFileTypes;
extern G__linked_taginfo G__BaseCintLN_TVirtualPS;
extern G__linked_taginfo G__BaseCintLN_TGTab;
extern G__linked_taginfo G__BaseCintLN_TGStatusBar;
extern G__linked_taginfo G__BaseCintLN_TGTabElement;
extern G__linked_taginfo G__BaseCintLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__BaseCintLN_MStatusDisplaycLcLStatus_t;
extern G__linked_taginfo G__BaseCintLN_MStatusDisplaycLcLdA;
extern G__linked_taginfo G__BaseCintLN_MArrayI;
extern G__linked_taginfo G__BaseCintLN_MLut;
extern G__linked_taginfo G__BaseCintLN_MArray;
extern G__linked_taginfo G__BaseCintLN_MArrayB;
extern G__linked_taginfo G__BaseCintLN_MArrayS;
extern G__linked_taginfo G__BaseCintLN_TArrayF;
extern G__linked_taginfo G__BaseCintLN_MArrayF;
extern G__linked_taginfo G__BaseCintLN_timeval;
extern G__linked_taginfo G__BaseCintLN_MTime;
extern G__linked_taginfo G__BaseCintLN_MTimecLcLdA;
extern G__linked_taginfo G__BaseCintLN_MClone;
extern G__linked_taginfo G__BaseCintLN_MContinue;
extern G__linked_taginfo G__BaseCintLN_MContinuecLcLdA;
extern G__linked_taginfo G__BaseCintLN_MPrint;
extern G__linked_taginfo G__BaseCintLN_MPrintcLcLdA;
extern G__linked_taginfo G__BaseCintLN_TThread;
extern G__linked_taginfo G__BaseCintLN_TThreadcLcLEState;
extern G__linked_taginfo G__BaseCintLN_MThread;
extern G__linked_taginfo G__BaseCintLN_MObjLookup;
extern G__linked_taginfo G__BaseCintLN_MObjLookupcLcLdA;

/* STUB derived class for protected member access */
