/********************************************************************
* MainCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MainCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMainCint();
extern void G__cpp_setup_inheritanceMainCint();
extern void G__cpp_setup_typetableMainCint();
extern void G__cpp_setup_memvarMainCint();
extern void G__cpp_setup_globalMainCint();
extern void G__cpp_setup_memfuncMainCint();
extern void G__cpp_setup_funcMainCint();
extern void G__set_cpp_environmentMainCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MBrowser.h"
#include "MEventDisplay.h"
#include "MCameraDisplay.h"
#include "MainIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MainCintLN_TClass;
extern G__linked_taginfo G__MainCintLN_TBuffer;
extern G__linked_taginfo G__MainCintLN_TMemberInspector;
extern G__linked_taginfo G__MainCintLN_TObject;
extern G__linked_taginfo G__MainCintLN_TString;
extern G__linked_taginfo G__MainCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MainCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MainCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MainCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MainCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MainCintLN_TCanvas;
extern G__linked_taginfo G__MainCintLN_TGObject;
extern G__linked_taginfo G__MainCintLN_TQObject;
extern G__linked_taginfo G__MainCintLN_TGWindow;
extern G__linked_taginfo G__MainCintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__MainCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__MainCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MainCintLN_TGFrame;
extern G__linked_taginfo G__MainCintLN_TGCompositeFrame;
extern G__linked_taginfo G__MainCintLN_TGHorizontalFrame;
extern G__linked_taginfo G__MainCintLN_TGMainFrame;
extern G__linked_taginfo G__MainCintLN_MGList;
extern G__linked_taginfo G__MainCintLN_TGTab;
extern G__linked_taginfo G__MainCintLN_TGListView;
extern G__linked_taginfo G__MainCintLN_TGTextEntry;
extern G__linked_taginfo G__MainCintLN_TGProgressBar;
extern G__linked_taginfo G__MainCintLN_TGFileContainer;
extern G__linked_taginfo G__MainCintLN_MBrowser;
extern G__linked_taginfo G__MainCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MainCintLN_MStatusDisplay;
extern G__linked_taginfo G__MainCintLN_TGLabel;
extern G__linked_taginfo G__MainCintLN_MEvtLoop;
extern G__linked_taginfo G__MainCintLN_MEventDisplay;
extern G__linked_taginfo G__MainCintLN_MEventDisplaycLcLdA;
extern G__linked_taginfo G__MainCintLN_MCameraDisplay;

/* STUB derived class for protected member access */
