/********************************************************************
* HCalibCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HCalibCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHCalibCint();
extern void G__cpp_setup_inheritanceHCalibCint();
extern void G__cpp_setup_typetableHCalibCint();
extern void G__cpp_setup_memvarHCalibCint();
extern void G__cpp_setup_globalHCalibCint();
extern void G__cpp_setup_memfuncHCalibCint();
extern void G__cpp_setup_funcHCalibCint();
extern void G__set_cpp_environmentHCalibCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MHCalibrationCam.h"
#include "MHCalibrationPix.h"
#include "MHCalibrationChargeCam.h"
#include "MHCalibrationChargePix.h"
#include "MHCalibrationChargeBlindCam.h"
#include "MHCalibrationChargeBlindPix.h"
#include "MHCalibrationChargePINDiode.h"
#include "MHCalibrationRelTimeCam.h"
#include "MHCalibrationPulseTimeCam.h"
#include "MHGausEvents.h"
#include "HCalibIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HCalibCintLN_TClass;
extern G__linked_taginfo G__HCalibCintLN_TBuffer;
extern G__linked_taginfo G__HCalibCintLN_TMemberInspector;
extern G__linked_taginfo G__HCalibCintLN_TObject;
extern G__linked_taginfo G__HCalibCintLN_TString;
extern G__linked_taginfo G__HCalibCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HCalibCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HCalibCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HCalibCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HCalibCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HCalibCintLN_MArrayI;
extern G__linked_taginfo G__HCalibCintLN_MArrayF;
extern G__linked_taginfo G__HCalibCintLN_TEnv;
extern G__linked_taginfo G__HCalibCintLN_MParContainer;
extern G__linked_taginfo G__HCalibCintLN_TH1I;
extern G__linked_taginfo G__HCalibCintLN_MArrayD;
extern G__linked_taginfo G__HCalibCintLN_MParList;
extern G__linked_taginfo G__HCalibCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HCalibCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HCalibCintLN_TF1;
extern G__linked_taginfo G__HCalibCintLN_TH1F;
extern G__linked_taginfo G__HCalibCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HCalibCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HCalibCintLN_MH;
extern G__linked_taginfo G__HCalibCintLN_MGeomCam;
extern G__linked_taginfo G__HCalibCintLN_MCamEvent;
extern G__linked_taginfo G__HCalibCintLN_MBadPixelsPix;
extern G__linked_taginfo G__HCalibCintLN_MBadPixelsPixcLcLUncalibratedType_t;
extern G__linked_taginfo G__HCalibCintLN_TOrdCollection;
extern G__linked_taginfo G__HCalibCintLN_MCalibrationPix;
extern G__linked_taginfo G__HCalibCintLN_MBadPixelsCam;
extern G__linked_taginfo G__HCalibCintLN_MCalibrationCam;
extern G__linked_taginfo G__HCalibCintLN_MCalibrationCamcLcLPulserColor_t;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationPix;
extern G__linked_taginfo G__HCalibCintLN_MRawRunHeader;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationCam;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationCamcLcLdA;
extern G__linked_taginfo G__HCalibCintLN_TGraph;
extern G__linked_taginfo G__HCalibCintLN_MHGausEvents;
extern G__linked_taginfo G__HCalibCintLN_MHGausEventscLcLdA;
extern G__linked_taginfo G__HCalibCintLN_MExtractedSignalCam;
extern G__linked_taginfo G__HCalibCintLN_MCalibrationChargePix;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationChargePix;
extern G__linked_taginfo G__HCalibCintLN_MPedestalSubtractedEvt;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationChargeCam;
extern G__linked_taginfo G__HCalibCintLN_TPaveText;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationChargeBlindPix;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationChargeBlindPixcLcLdA;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationChargeBlindPixcLcLFitFunc_t;
extern G__linked_taginfo G__HCalibCintLN_MRawEvtData;
extern G__linked_taginfo G__HCalibCintLN_MCalibrationBlindPix;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationChargeBlindCam;
extern G__linked_taginfo G__HCalibCintLN_MExtractedSignalPINDiode;
extern G__linked_taginfo G__HCalibCintLN_MCalibrationChargePINDiode;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationChargePINDiode;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationRelTimeCam;
extern G__linked_taginfo G__HCalibCintLN_MHCalibrationPulseTimeCam;

/* STUB derived class for protected member access */
