/********************************************************************
* HBaseCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HBaseCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHBaseCint();
extern void G__cpp_setup_inheritanceHBaseCint();
extern void G__cpp_setup_typetableHBaseCint();
extern void G__cpp_setup_memvarHBaseCint();
extern void G__cpp_setup_globalHBaseCint();
extern void G__cpp_setup_memfuncHBaseCint();
extern void G__cpp_setup_funcHBaseCint();
extern void G__set_cpp_environmentHBaseCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MFillH.h"
#include "MBinning.h"
#include "MH.h"
#include "MH3.h"
#include "MHn.h"
#include "MHArray.h"
#include "MHMatrix.h"
#include "HBaseIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HBaseCintLN_TClass;
extern G__linked_taginfo G__HBaseCintLN_TBuffer;
extern G__linked_taginfo G__HBaseCintLN_TMemberInspector;
extern G__linked_taginfo G__HBaseCintLN_TObject;
extern G__linked_taginfo G__HBaseCintLN_TCollection;
extern G__linked_taginfo G__HBaseCintLN_TString;
extern G__linked_taginfo G__HBaseCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__HBaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HBaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HBaseCintLN_TList;
extern G__linked_taginfo G__HBaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HBaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HBaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HBaseCintLN_TCanvas;
extern G__linked_taginfo G__HBaseCintLN_TVirtualPad;
extern G__linked_taginfo G__HBaseCintLN_TEnv;
extern G__linked_taginfo G__HBaseCintLN_TArrayD;
extern G__linked_taginfo G__HBaseCintLN_MParContainer;
extern G__linked_taginfo G__HBaseCintLN_MInputStreamID;
extern G__linked_taginfo G__HBaseCintLN_MFilter;
extern G__linked_taginfo G__HBaseCintLN_MParList;
extern G__linked_taginfo G__HBaseCintLN_MTask;
extern G__linked_taginfo G__HBaseCintLN_MH;
extern G__linked_taginfo G__HBaseCintLN_MMap;
extern G__linked_taginfo G__HBaseCintLN_MData;
extern G__linked_taginfo G__HBaseCintLN_MParameterD;
extern G__linked_taginfo G__HBaseCintLN_MFillH;
extern G__linked_taginfo G__HBaseCintLN_MFillHcLcLdA;
extern G__linked_taginfo G__HBaseCintLN_TH1;
extern G__linked_taginfo G__HBaseCintLN_TAxis;
extern G__linked_taginfo G__HBaseCintLN_MBinning;
extern G__linked_taginfo G__HBaseCintLN_MBinningcLcLdA;
extern G__linked_taginfo G__HBaseCintLN_TH1I;
extern G__linked_taginfo G__HBaseCintLN_TH2;
extern G__linked_taginfo G__HBaseCintLN_TH3;
extern G__linked_taginfo G__HBaseCintLN_TArrayF;
extern G__linked_taginfo G__HBaseCintLN_MArrayF;
extern G__linked_taginfo G__HBaseCintLN_MArrayD;
extern G__linked_taginfo G__HBaseCintLN_TProfile;
extern G__linked_taginfo G__HBaseCintLN_TArrayI;
extern G__linked_taginfo G__HBaseCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HBaseCintLN_TH1F;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HBaseCintLN_MObjLookup;
extern G__linked_taginfo G__HBaseCintLN_TFormula;
extern G__linked_taginfo G__HBaseCintLN_MH3;
extern G__linked_taginfo G__HBaseCintLN_MH3cLcLLabels_t;
extern G__linked_taginfo G__HBaseCintLN_MH3cLcLType_t;
extern G__linked_taginfo G__HBaseCintLN_MH3cLcLdA;
extern G__linked_taginfo G__HBaseCintLN_MHn;
extern G__linked_taginfo G__HBaseCintLN_MHncLcLLayout_t;
extern G__linked_taginfo G__HBaseCintLN_MHncLcLdA;
extern G__linked_taginfo G__HBaseCintLN_TLegend;
extern G__linked_taginfo G__HBaseCintLN_MHArray;
extern G__linked_taginfo G__HBaseCintLN_MHArraycLcLdA;
extern G__linked_taginfo G__HBaseCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__HBaseCintLN_MDataArray;
extern G__linked_taginfo G__HBaseCintLN_MHMatrix;
extern G__linked_taginfo G__HBaseCintLN_MHMatrixcLcLdA;

/* STUB derived class for protected member access */
