//
// File generated by rootcint at Mon Nov 28 11:05:43 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ExtralgoCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ExtralgoCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::MExtralgoSpline MExtralgoSpline;
      #else
      class MExtralgoSpline  {
         public:
         //friend XX;
         #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
         typedef ::MExtralgoSpline::ExtractionType_t ExtractionType_t;
         #else
         enum ExtractionType_t  {
         };
         #endif

         ExtractionType_t fExtractionType; //
          float* fVal; //
          int fNum; //
         float* fDer1; //
         float* fDer2; //
         float fRiseTime; //
         float fFallTime; //
         float fHeightTm; //
         float fTime; //
         float fTimeDev; //
         float fWidth; //
         float fWidthDev; //
         float fSignal; //
         float fSignalDev; //
         float fHeight; //
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::MExtralgoDigitalFilter MExtralgoDigitalFilter;
      #else
      class MExtralgoDigitalFilter  {
         public:
         //friend XX;
          float* fVal; //
         int fNum; //
          float* fWeightsAmp; //
          float* fWeightsTime; //
          float* fPulseShape; //
         :: TMatrixT< float >* fAinv; //
          int fWeightsPerBin; //Number of weights per data bin
          int fWindowSize; //
         float fTime; //
         float fTimeDev; //
         float fSignal; //
         float fSignalDev; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void MExtralgoSpline_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void MExtralgoSpline_Dictionary();
   static void delete_MExtralgoSpline(void *p);
   static void deleteArray_MExtralgoSpline(void *p);
   static void destruct_MExtralgoSpline(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MExtralgoSpline*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::MExtralgoSpline) == sizeof( ::ROOTShadow::Shadow::MExtralgoSpline));
      ::MExtralgoSpline *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::MExtralgoSpline),0);
      static ::ROOT::TGenericClassInfo 
         instance("MExtralgoSpline", "./MExtralgoSpline.h", 12,
                  typeid(::MExtralgoSpline), ::ROOT::DefineBehavior(ptr, ptr),
                  &MExtralgoSpline_ShowMembers, &MExtralgoSpline_Dictionary, isa_proxy, 4,
                  sizeof(::MExtralgoSpline) );
      instance.SetDelete(&delete_MExtralgoSpline);
      instance.SetDeleteArray(&deleteArray_MExtralgoSpline);
      instance.SetDestructor(&destruct_MExtralgoSpline);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MExtralgoSpline*)
   {
      return GenerateInitInstanceLocal((::MExtralgoSpline*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MExtralgoSpline*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void MExtralgoSpline_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::MExtralgoSpline*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void MExtralgoDigitalFilter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void MExtralgoDigitalFilter_Dictionary();
   static void delete_MExtralgoDigitalFilter(void *p);
   static void deleteArray_MExtralgoDigitalFilter(void *p);
   static void destruct_MExtralgoDigitalFilter(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MExtralgoDigitalFilter*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::MExtralgoDigitalFilter) == sizeof( ::ROOTShadow::Shadow::MExtralgoDigitalFilter));
      ::MExtralgoDigitalFilter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::MExtralgoDigitalFilter),0);
      static ::ROOT::TGenericClassInfo 
         instance("MExtralgoDigitalFilter", "./MExtralgoDigitalFilter.h", 15,
                  typeid(::MExtralgoDigitalFilter), ::ROOT::DefineBehavior(ptr, ptr),
                  &MExtralgoDigitalFilter_ShowMembers, &MExtralgoDigitalFilter_Dictionary, isa_proxy, 4,
                  sizeof(::MExtralgoDigitalFilter) );
      instance.SetDelete(&delete_MExtralgoDigitalFilter);
      instance.SetDeleteArray(&deleteArray_MExtralgoDigitalFilter);
      instance.SetDestructor(&destruct_MExtralgoDigitalFilter);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MExtralgoDigitalFilter*)
   {
      return GenerateInitInstanceLocal((::MExtralgoDigitalFilter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MExtralgoDigitalFilter*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void MExtralgoDigitalFilter_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::MExtralgoDigitalFilter*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void MExtralgoSpline_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class MExtralgoSpline.
      typedef ::ROOTShadow::Shadow::MExtralgoSpline ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::MExtralgoSpline*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fExtractionType", &sobj->fExtractionType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVal", &sobj->fVal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNum", &sobj->fNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDer1", &sobj->fDer1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDer2", &sobj->fDer2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRiseTime", &sobj->fRiseTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fFallTime", &sobj->fFallTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fHeightTm", &sobj->fHeightTm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &sobj->fTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTimeDev", &sobj->fTimeDev);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWidth", &sobj->fWidth);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWidthDev", &sobj->fWidthDev);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSignal", &sobj->fSignal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSignalDev", &sobj->fSignalDev);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fHeight", &sobj->fHeight);
   }

}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_MExtralgoSpline(void *p) {
      delete ((::MExtralgoSpline*)p);
   }
   static void deleteArray_MExtralgoSpline(void *p) {
      delete [] ((::MExtralgoSpline*)p);
   }
   static void destruct_MExtralgoSpline(void *p) {
      typedef ::MExtralgoSpline current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::MExtralgoSpline

//______________________________________________________________________________
namespace ROOTDict {
   void MExtralgoDigitalFilter_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class MExtralgoDigitalFilter.
      typedef ::ROOTShadow::Shadow::MExtralgoDigitalFilter ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::MExtralgoDigitalFilter*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVal", &sobj->fVal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNum", &sobj->fNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fWeightsAmp", &sobj->fWeightsAmp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fWeightsTime", &sobj->fWeightsTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPulseShape", &sobj->fPulseShape);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fAinv", &sobj->fAinv);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWeightsPerBin", &sobj->fWeightsPerBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWindowSize", &sobj->fWindowSize);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &sobj->fTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTimeDev", &sobj->fTimeDev);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSignal", &sobj->fSignal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSignalDev", &sobj->fSignalDev);
   }

}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_MExtralgoDigitalFilter(void *p) {
      delete ((::MExtralgoDigitalFilter*)p);
   }
   static void deleteArray_MExtralgoDigitalFilter(void *p) {
      delete [] ((::MExtralgoDigitalFilter*)p);
   }
   static void destruct_MExtralgoDigitalFilter(void *p) {
      typedef ::MExtralgoDigitalFilter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::MExtralgoDigitalFilter

/********************************************************
* ExtralgoCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableExtralgoCint();

extern "C" void G__set_cpp_environmentExtralgoCint() {
  G__cpp_reset_tagtableExtralgoCint();
}
#include <new>
extern "C" int G__cpp_dllrevExtralgoCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MExtralgoSpline */
static int G__ExtralgoCint_115_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MExtralgoSpline* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MExtralgoSpline(
(Float_t*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) MExtralgoSpline(
(Float_t*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSpline));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MExtralgoSpline*) G__getstructoffset())->SetRiseFallTime((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MExtralgoSpline*) G__getstructoffset())->SetExtractionType((MExtralgoSpline::ExtractionType_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MExtralgoSpline*) G__getstructoffset())->SetHeightTm((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetWidth());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetSignal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetHeight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetTimeDev());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetWidthDev());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetSignalDev());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const MExtralgoSpline*) G__getstructoffset())->GetSignal(*(Float_t*) G__Floatref(&libp->para[0]), *(Float_t*) G__Floatref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const MExtralgoSpline*) G__getstructoffset())->GetWidth(*(Float_t*) G__Floatref(&libp->para[0]), *(Float_t*) G__Floatref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const MExtralgoSpline*) G__getstructoffset())->GetTime(*(Float_t*) G__Floatref(&libp->para[0]), *(Float_t*) G__Floatref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((MExtralgoSpline*) G__getstructoffset())->ExtractNoise());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((MExtralgoSpline*) G__getstructoffset())->Extract((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((MExtralgoSpline*) G__getstructoffset())->Extract((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->EvalAt((const Float_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->Deriv1((const Float_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const MExtralgoSpline*) G__getstructoffset())->SearchYdn((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const MExtralgoSpline*) G__getstructoffset())->SearchYup((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const MExtralgoSpline*) G__getstructoffset())->SearchYdn((Float_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const MExtralgoSpline*) G__getstructoffset())->SearchYup((Float_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      {
         const MArrayF* pobj;
         const MArrayF xobj = ((const MExtralgoSpline*) G__getstructoffset())->GetIntegral((bool) G__int(libp->para[0]));
         pobj = new MArrayF(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   case 0:
      {
         const MArrayF* pobj;
         const MArrayF xobj = ((const MExtralgoSpline*) G__getstructoffset())->GetIntegral();
         pobj = new MArrayF(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_115_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoSpline*) G__getstructoffset())->GetIntegral((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ExtralgoCint_115_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MExtralgoSpline* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MExtralgoSpline(*(MExtralgoSpline*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSpline));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MExtralgoSpline G__TMExtralgoSpline;
static int G__ExtralgoCint_115_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MExtralgoSpline*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MExtralgoSpline*) (soff+(sizeof(MExtralgoSpline)*i)))->~G__TMExtralgoSpline();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MExtralgoSpline*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MExtralgoSpline*) (soff))->~G__TMExtralgoSpline();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* MExtralgoDigitalFilter */
static int G__ExtralgoCint_171_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MExtralgoDigitalFilter* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 6:
     //m: 6
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MExtralgoDigitalFilter(
(Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3])
, (Float_t*) G__int(libp->para[4]), (TMatrix*) G__int(libp->para[5]));
     } else {
       p = new((void*) gvp) MExtralgoDigitalFilter(
(Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3])
, (Float_t*) G__int(libp->para[4]), (TMatrix*) G__int(libp->para[5]));
     }
     break;
   case 5:
     //m: 5
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MExtralgoDigitalFilter(
(Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3])
, (Float_t*) G__int(libp->para[4]));
     } else {
       p = new((void*) gvp) MExtralgoDigitalFilter(
(Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3])
, (Float_t*) G__int(libp->para[4]));
     }
     break;
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MExtralgoDigitalFilter(
(Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) MExtralgoDigitalFilter(
(Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Float_t*) G__int(libp->para[2]), (Float_t*) G__int(libp->para[3]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoDigitalFilter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MExtralgoDigitalFilter*) G__getstructoffset())->SetData((Int_t) G__int(libp->para[0]), (Float_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoDigitalFilter*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoDigitalFilter*) G__getstructoffset())->GetSignal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoDigitalFilter*) G__getstructoffset())->GetTimeDev());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoDigitalFilter*) G__getstructoffset())->GetSignalDev());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const MExtralgoDigitalFilter*) G__getstructoffset())->GetSignal(*(Float_t*) G__Floatref(&libp->para[0]), *(Float_t*) G__Floatref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const MExtralgoDigitalFilter*) G__getstructoffset())->GetTime(*(Float_t*) G__Floatref(&libp->para[0]), *(Float_t*) G__Floatref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const MExtralgoDigitalFilter*) G__getstructoffset())->ExtractNoise());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((MExtralgoDigitalFilter*) G__getstructoffset())->Extract((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((MExtralgoDigitalFilter*) G__getstructoffset())->Extract();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 105, (long) MExtralgoDigitalFilter::CalculateWeights(*(TH1*) libp->para[0].ref, *(TH2*) libp->para[1].ref
, *(TArrayF*) libp->para[2].ref, *(TArrayF*) libp->para[3].ref
, (Int_t) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 105, (long) MExtralgoDigitalFilter::CalculateWeights(*(TH1*) libp->para[0].ref, *(TH2*) libp->para[1].ref
, *(TArrayF*) libp->para[2].ref, *(TArrayF*) libp->para[3].ref));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExtralgoCint_171_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 105, (long) MExtralgoDigitalFilter::CalculateWeights2(*(TH1*) libp->para[0].ref, *(TH2*) libp->para[1].ref
, *(TArrayF*) libp->para[2].ref, *(TArrayF*) libp->para[3].ref
, (Int_t) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 105, (long) MExtralgoDigitalFilter::CalculateWeights2(*(TH1*) libp->para[0].ref, *(TH2*) libp->para[1].ref
, *(TArrayF*) libp->para[2].ref, *(TArrayF*) libp->para[3].ref));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ExtralgoCint_171_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MExtralgoDigitalFilter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MExtralgoDigitalFilter(*(MExtralgoDigitalFilter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoDigitalFilter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MExtralgoDigitalFilter G__TMExtralgoDigitalFilter;
static int G__ExtralgoCint_171_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MExtralgoDigitalFilter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MExtralgoDigitalFilter*) (soff+(sizeof(MExtralgoDigitalFilter)*i)))->~G__TMExtralgoDigitalFilter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MExtralgoDigitalFilter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MExtralgoDigitalFilter*) (soff))->~G__TMExtralgoDigitalFilter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MExtralgoSpline */

/* MExtralgoDigitalFilter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncExtralgoCint {
 public:
  G__Sizep2memfuncExtralgoCint(): p(&G__Sizep2memfuncExtralgoCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncExtralgoCint::*p)();
};

size_t G__get_sizep2memfuncExtralgoCint()
{
  G__Sizep2memfuncExtralgoCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceExtralgoCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableExtralgoCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExtralgoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExtralgoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExtralgoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExtralgoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrix",117,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MExtralgoSpline */
static void G__setup_memvarMExtralgoSpline(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSpline));
   { MExtralgoSpline *p; p=(MExtralgoSpline*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLdA),-1,-2,4,"kIntegral=1LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLdA),-1,-2,4,"kTimeRel=2LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLdA),-1,-2,4,"kMaximum=4LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLdA),-1,-2,4,"kDynWidth=8LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLdA),-1,-2,4,"kFixedWidth=16LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-2,1,G__FastAllocString(2048).Format("kAmplitudeAbs=%lldLL",(long long)MExtralgoSpline::kAmplitudeAbs).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-2,1,G__FastAllocString(2048).Format("kAmplitudeRel=%lldLL",(long long)MExtralgoSpline::kAmplitudeRel).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-2,1,G__FastAllocString(2048).Format("kAmplitude=%lldLL",(long long)MExtralgoSpline::kAmplitude).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-2,1,G__FastAllocString(2048).Format("kIntegralAbs=%lldLL",(long long)MExtralgoSpline::kIntegralAbs).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-2,1,G__FastAllocString(2048).Format("kIntegralRel=%lldLL",(long long)MExtralgoSpline::kIntegralRel).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-2,1,G__FastAllocString(2048).Format("kIntegralDyn=%lldLL",(long long)MExtralgoSpline::kIntegralDyn).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-2,1,G__FastAllocString(2048).Format("kIntegralFixed=%lldLL",(long long)MExtralgoSpline::kIntegralFixed).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t),-1,-1,4,"fExtractionType=",0,(char*)NULL);
   G__memvar_setup((void*)0,70,0,1,-1,G__defined_typename("Float_t"),-1,4,"fVal=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,1,-1,G__defined_typename("Int_t"),-1,4,"fNum=",0,(char*)NULL);
   G__memvar_setup((void*)0,70,0,0,-1,G__defined_typename("Float_t"),-1,4,"fDer1=",0,(char*)NULL);
   G__memvar_setup((void*)0,70,0,0,-1,G__defined_typename("Float_t"),-1,4,"fDer2=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fRiseTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fFallTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fHeightTm=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fTimeDev=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fWidth=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fWidthDev=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fSignal=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fSignalDev=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fHeight=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* MExtralgoDigitalFilter */
static void G__setup_memvarMExtralgoDigitalFilter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoDigitalFilter));
   { MExtralgoDigitalFilter *p; p=(MExtralgoDigitalFilter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,70,0,1,-1,G__defined_typename("Float_t"),-1,4,"fVal=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNum=",0,(char*)NULL);
   G__memvar_setup((void*)0,70,0,1,-1,G__defined_typename("Float_t"),-1,4,"fWeightsAmp=",0,(char*)NULL);
   G__memvar_setup((void*)0,70,0,1,-1,G__defined_typename("Float_t"),-1,4,"fWeightsTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,70,0,1,-1,G__defined_typename("Float_t"),-1,4,"fPulseShape=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__ExtralgoCintLN_TMatrixTlEfloatgR),G__defined_typename("TMatrix"),-1,4,"fAinv=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,1,-1,G__defined_typename("Int_t"),-1,4,"fWeightsPerBin=",0,"Number of weights per data bin");
   G__memvar_setup((void*)0,105,0,1,-1,G__defined_typename("Int_t"),-1,4,"fWindowSize=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fTimeDev=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fSignal=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fSignalDev=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarExtralgoCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMExtralgoSpline(void) {
   /* MExtralgoSpline */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSpline));
   G__memfunc_setup("ReMul",485,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 4, 8, 
"u 'TComplex' - 11 - c1 u 'TComplex' - 11 - th", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Eval",392,(G__InterfaceMethod) NULL, 102, -1, G__defined_typename("Float_t"), 0, 3, 1, 4, 8, 
"f - 'Float_t' 0 - val f - 'Float_t' 0 - a "
"f - 'Float_t' 0 - deriv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Eval",392,(G__InterfaceMethod) NULL, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 4, 8, 
"i - 'Int_t' 10 - i f - 'Float_t' 10 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalDeriv1",947,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 4, 8, 
"i - 'Int_t' 10 - i f - 'Float_t' 10 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalDeriv2",948,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 4, 8, 
"i - 'Int_t' 10 - i f - 'Float_t' 10 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SolvePol3",871,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 5, 1, 4, 8, 
"i - 'Int_t' 0 - i d - 'Double_t' 0 - y "
"d - 'Double_t' 1 - x1 d - 'Double_t' 1 - x2 "
"d - 'Double_t' 1 - x3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindYdn",684,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 4, 8, 
"i - 'Int_t' 0 - i d - 'Double_t' 0 '0' y "
"d - 'Double_t' 0 '0' min d - 'Double_t' 0 '1' max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindYup",703,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 4, 8, 
"i - 'Int_t' 0 - i d - 'Double_t' 0 '0' y "
"d - 'Double_t' 0 '0' min d - 'Double_t' 0 '1' max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalDerivEq0",1128,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 3, 1, 4, 8, 
"i - 'Int_t' 10 - i d - 'Double_t' 1 - x1 "
"d - 'Double_t' 1 - x2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalPrimitive",1345,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 4, 8, 
"i - 'Int_t' 0 - i f - 'Float_t' 0 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Align",491,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 8, 
"i - 'Int_t' 1 - i f - 'Float_t' 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalInteg",895,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 4, 8, 
"i - 'Int_t' 0 - i f - 'Float_t' 0 - a "
"f - 'Float_t' 0 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalInteg",895,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 4, 8, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalInteg",895,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 4, 8, 
"i - 'Int_t' 0 - a i - 'Int_t' 0 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalInteg",895,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 4, 8, 
"f - 'Float_t' 0 - x0 f - 'Float_t' 0 - x1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMaxAroundI",1272,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 8, 
"i - 'Int_t' 0 - i f - 'Float_t' 1 - xmax "
"f - 'Float_t' 1 - ymax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMax",582,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 5, 1, 4, 8, 
"i - 'Int_t' 0 - i f - 'Float_t' 1 - xmax "
"f - 'Float_t' 1 - ymax f - 'Float_t' 0 '0' min "
"f - 'Float_t' 0 '1' max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitDerivatives",1562,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcIntegral",1193,(G__InterfaceMethod) NULL, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 4, 8, "f - 'Float_t' 0 - start", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcIntegral",1193,(G__InterfaceMethod) NULL, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 4, 8, 
"f - 'Float_t' 0 - beg f - 'Float_t' 0 - width", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MExtralgoSpline",1534,G__ExtralgoCint_115_0_21, 105, G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSpline), -1, 0, 4, 1, 1, 0, 
"F - 'Float_t' 10 - val i - 'Int_t' 0 - n "
"F - 'Float_t' 0 - der1 F - 'Float_t' 0 - der2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRiseFallTime",1485,G__ExtralgoCint_115_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"f - 'Float_t' 0 - rise f - 'Float_t' 0 - fall", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetExtractionType",1775,G__ExtralgoCint_115_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i 'MExtralgoSpline::ExtractionType_t' - 0 - typ", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHeightTm",1094,G__ExtralgoCint_115_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__ExtralgoCint_115_0_25, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWidth",800,G__ExtralgoCint_115_0_26, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSignal",894,G__ExtralgoCint_115_0_27, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHeight",889,G__ExtralgoCint_115_0_28, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimeDev",974,G__ExtralgoCint_115_0_29, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWidthDev",1087,G__ExtralgoCint_115_0_30, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSignalDev",1181,G__ExtralgoCint_115_0_31, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSignal",894,G__ExtralgoCint_115_0_32, 121, -1, -1, 0, 2, 1, 1, 8, 
"f - 'Float_t' 1 - sig f - 'Float_t' 1 - dsig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWidth",800,G__ExtralgoCint_115_0_33, 121, -1, -1, 0, 2, 1, 1, 8, 
"f - 'Float_t' 1 - sig f - 'Float_t' 1 - dsig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__ExtralgoCint_115_0_34, 121, -1, -1, 0, 2, 1, 1, 8, 
"f - 'Float_t' 1 - sig f - 'Float_t' 1 - dsig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ExtractNoise",1241,G__ExtralgoCint_115_0_35, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Extract",731,G__ExtralgoCint_115_0_36, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - maxpos g - 'Bool_t' 0 'kFALSE' width", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EvalAt",573,G__ExtralgoCint_115_0_37, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 8, "f - 'Float_t' 10 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Deriv1",555,G__ExtralgoCint_115_0_38, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 8, "f - 'Float_t' 10 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SearchYdn",897,G__ExtralgoCint_115_0_39, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"d - 'Double_t' 0 - maxpos d - 'Double_t' 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SearchYup",916,G__ExtralgoCint_115_0_40, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"d - 'Double_t' 0 - maxpos d - 'Double_t' 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SearchYdn",897,G__ExtralgoCint_115_0_41, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "f - 'Float_t' 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SearchYup",916,G__ExtralgoCint_115_0_42, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "f - 'Float_t' 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIntegral",1110,G__ExtralgoCint_115_0_43, 117, G__get_linked_tagnum(&G__ExtralgoCintLN_MArrayF), -1, 0, 1, 1, 1, 8, "g - - 0 'false' norm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIntegral",1110,G__ExtralgoCint_115_0_44, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 1, 8, 
"f - 'Float_t' 0 - beg f - 'Float_t' 0 - end", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("MExtralgoSpline", 1534, G__ExtralgoCint_115_0_45, (int) ('i'), G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoSpline), -1, 0, 1, 1, 1, 0, "u 'MExtralgoSpline' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MExtralgoSpline", 1660, G__ExtralgoCint_115_0_46, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncMExtralgoDigitalFilter(void) {
   /* MExtralgoDigitalFilter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoDigitalFilter));
   G__memfunc_setup("GetChisq",792,(G__InterfaceMethod) NULL, 102, -1, G__defined_typename("Float_t"), 0, 3, 1, 4, 8, 
"i - 'Int_t' 10 - maxp i - 'Int_t' 10 - frac "
"f - 'Float_t' 10 - sum", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChiSq",472,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 4, 8, 
"d - 'Double_t' 10 - sum i - 'Int_t' 10 - startv "
"i - 'Int_t' 10 '0' startw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Eval",392,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 4, 8, 
"F - 'Float_t' 40 - weights i - 'Int_t' 10 - startv "
"i - 'Int_t' 10 '0' startw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AlignIntoLimits",1527,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 8, 
"i - 'Int_t' 1 - maxp i - 'Int_t' 1 - frac", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AlignExtractionWindow",2180,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 3, 1, 4, 0, 
"i - 'Int_t' 1 - maxp i - 'Int_t' 1 - frac "
"d - 'Double_t' 10 - ampsum", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AlignExtractionWindow",2180,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"i - 'Int_t' 1 - maxp i - 'Int_t' 1 - frac", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MExtralgoDigitalFilter",2231,G__ExtralgoCint_171_0_7, 105, G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoDigitalFilter), -1, 0, 6, 1, 1, 0, 
"i - 'Int_t' 0 - res i - 'Int_t' 0 - windowsize "
"F - 'Float_t' 0 - wa F - 'Float_t' 0 - wt "
"F - 'Float_t' 0 '0' ps U 'TMatrixT<float>' 'TMatrix' 0 '0' ainv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetData",678,G__ExtralgoCint_171_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - n F - 'Float_t' 40 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__ExtralgoCint_171_0_9, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSignal",894,G__ExtralgoCint_171_0_10, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimeDev",974,G__ExtralgoCint_171_0_11, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSignalDev",1181,G__ExtralgoCint_171_0_12, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSignal",894,G__ExtralgoCint_171_0_13, 121, -1, -1, 0, 2, 1, 1, 8, 
"f - 'Float_t' 1 - sig f - 'Float_t' 1 - dsig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__ExtralgoCint_171_0_14, 121, -1, -1, 0, 2, 1, 1, 8, 
"f - 'Float_t' 1 - sig f - 'Float_t' 1 - dsig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ExtractNoise",1241,G__ExtralgoCint_171_0_15, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Extract",731,G__ExtralgoCint_171_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '-1' maxpos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateWeights",1641,G__ExtralgoCint_171_0_17, 105, -1, G__defined_typename("Int_t"), 0, 5, 3, 1, 0, 
"u 'TH1' - 1 - shape u 'TH2' - 11 - autocorr "
"u 'TArrayF' - 1 - wa u 'TArrayF' - 1 - wt "
"i - 'Int_t' 0 '-1' wpb", (char*)NULL, (void*) G__func2void( (Int_t (*)(TH1&, const TH2&, TArrayF&, TArrayF&, Int_t))(&MExtralgoDigitalFilter::CalculateWeights) ), 0);
   G__memfunc_setup("CalculateWeights2",1691,G__ExtralgoCint_171_0_18, 105, -1, G__defined_typename("Int_t"), 0, 5, 3, 1, 0, 
"u 'TH1' - 1 - shape u 'TH2' - 11 - autocorr "
"u 'TArrayF' - 1 - wa u 'TArrayF' - 1 - wt "
"i - 'Int_t' 0 '-1' wpb", (char*)NULL, (void*) G__func2void( (Int_t (*)(TH1&, const TH2&, TArrayF&, TArrayF&, Int_t))(&MExtralgoDigitalFilter::CalculateWeights2) ), 0);
   // automatic copy constructor
   G__memfunc_setup("MExtralgoDigitalFilter", 2231, G__ExtralgoCint_171_0_19, (int) ('i'), 
G__get_linked_tagnum(&G__ExtralgoCintLN_MExtralgoDigitalFilter), -1, 0, 1, 1, 1, 0, "u 'MExtralgoDigitalFilter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MExtralgoDigitalFilter", 2357, G__ExtralgoCint_171_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncExtralgoCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalExtralgoCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcExtralgoCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ExtralgoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_MArrayF = { "MArrayF" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TComplex = { "TComplex" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_MExtralgoSpline = { "MExtralgoSpline" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_MExtralgoSplinecLcLdA = { "MExtralgoSpline::$" , 101 , -1 };
G__linked_taginfo G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t = { "MExtralgoSpline::ExtractionType_t" , 101 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TH2 = { "TH2" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_TArrayF = { "TArrayF" , 99 , -1 };
G__linked_taginfo G__ExtralgoCintLN_MExtralgoDigitalFilter = { "MExtralgoDigitalFilter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableExtralgoCint() {
  G__ExtralgoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ExtralgoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExtralgoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ExtralgoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExtralgoCintLN_MArrayF.tagnum = -1 ;
  G__ExtralgoCintLN_TComplex.tagnum = -1 ;
  G__ExtralgoCintLN_MExtralgoSpline.tagnum = -1 ;
  G__ExtralgoCintLN_MExtralgoSplinecLcLdA.tagnum = -1 ;
  G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ExtralgoCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ExtralgoCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__ExtralgoCintLN_TH1.tagnum = -1 ;
  G__ExtralgoCintLN_TH2.tagnum = -1 ;
  G__ExtralgoCintLN_TArrayF.tagnum = -1 ;
  G__ExtralgoCintLN_MExtralgoDigitalFilter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableExtralgoCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_MArrayF);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TComplex);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_MExtralgoSpline),sizeof(MExtralgoSpline),-1,294912,(char*)NULL,G__setup_memvarMExtralgoSpline,G__setup_memfuncMExtralgoSpline);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_MExtralgoSplinecLcLdA);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TH1);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TH2);
   G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_TArrayF);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ExtralgoCintLN_MExtralgoDigitalFilter),sizeof(MExtralgoDigitalFilter),-1,294912,(char*)NULL,G__setup_memvarMExtralgoDigitalFilter,G__setup_memfuncMExtralgoDigitalFilter);
}
extern "C" void G__cpp_setupExtralgoCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupExtralgoCint()");
  G__set_cpp_environmentExtralgoCint();
  G__cpp_setup_tagtableExtralgoCint();

  G__cpp_setup_inheritanceExtralgoCint();

  G__cpp_setup_typetableExtralgoCint();

  G__cpp_setup_memvarExtralgoCint();

  G__cpp_setup_memfuncExtralgoCint();
  G__cpp_setup_globalExtralgoCint();
  G__cpp_setup_funcExtralgoCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncExtralgoCint();
  return;
}
class G__cpp_setup_initExtralgoCint {
  public:
    G__cpp_setup_initExtralgoCint() { G__add_setup_func("ExtralgoCint",(G__incsetup)(&G__cpp_setupExtralgoCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initExtralgoCint() { G__remove_setup_func("ExtralgoCint"); }
};
G__cpp_setup_initExtralgoCint G__cpp_setup_initializerExtralgoCint;

