/********************************************************************
* ExtralgoCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ExtralgoCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableExtralgoCint();
extern void G__cpp_setup_inheritanceExtralgoCint();
extern void G__cpp_setup_typetableExtralgoCint();
extern void G__cpp_setup_memvarExtralgoCint();
extern void G__cpp_setup_globalExtralgoCint();
extern void G__cpp_setup_memfuncExtralgoCint();
extern void G__cpp_setup_funcExtralgoCint();
extern void G__set_cpp_environmentExtralgoCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MExtralgoSpline.h"
#include "MExtralgoDigitalFilter.h"
#include "ExtralgoIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ExtralgoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ExtralgoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExtralgoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ExtralgoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExtralgoCintLN_MArrayF;
extern G__linked_taginfo G__ExtralgoCintLN_TComplex;
extern G__linked_taginfo G__ExtralgoCintLN_MExtralgoSpline;
extern G__linked_taginfo G__ExtralgoCintLN_MExtralgoSplinecLcLdA;
extern G__linked_taginfo G__ExtralgoCintLN_MExtralgoSplinecLcLExtractionType_t;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ExtralgoCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ExtralgoCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ExtralgoCintLN_TH1;
extern G__linked_taginfo G__ExtralgoCintLN_TH2;
extern G__linked_taginfo G__ExtralgoCintLN_TArrayF;
extern G__linked_taginfo G__ExtralgoCintLN_MExtralgoDigitalFilter;

/* STUB derived class for protected member access */
