/********************************************************************
* McCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error McCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMcCint();
extern void G__cpp_setup_inheritanceMcCint();
extern void G__cpp_setup_typetableMcCint();
extern void G__cpp_setup_memvarMcCint();
extern void G__cpp_setup_globalMcCint();
extern void G__cpp_setup_memfuncMcCint();
extern void G__cpp_setup_funcMcCint();
extern void G__set_cpp_environmentMcCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MMcTrigHeader.hxx"
#include "MMcFadcHeader.hxx"
#include "MMcRunHeader.hxx"
#include "MMcEvt.hxx"
#include "MMcTrig.hxx"
#include "MMcConfigRunHeader.h"
#include "MMcCorsikaRunHeader.h"
#include "MMcEvtBasic.h"
#include "McIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__McCintLN_TClass;
extern G__linked_taginfo G__McCintLN_TBuffer;
extern G__linked_taginfo G__McCintLN_TMemberInspector;
extern G__linked_taginfo G__McCintLN_TObject;
extern G__linked_taginfo G__McCintLN_TString;
extern G__linked_taginfo G__McCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__McCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McCintLN_TObjArray;
extern G__linked_taginfo G__McCintLN_TClonesArray;
extern G__linked_taginfo G__McCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__McCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__McCintLN_fits;
extern G__linked_taginfo G__McCintLN_MParContainer;
extern G__linked_taginfo G__McCintLN_MMcTrigHeader;
extern G__linked_taginfo G__McCintLN_MGeomCam;
extern G__linked_taginfo G__McCintLN_MCamEvent;
extern G__linked_taginfo G__McCintLN_MMcFadcHeader;
extern G__linked_taginfo G__McCintLN_MMcRunHeader;
extern G__linked_taginfo G__McCintLN_MMcEvtBasic;
extern G__linked_taginfo G__McCintLN_MMcEvtBasiccLcLParticleId_t;
extern G__linked_taginfo G__McCintLN_MMcEvt;
extern G__linked_taginfo G__McCintLN_MMcTrig;
extern G__linked_taginfo G__McCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__McCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__McCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__McCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__McCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__McCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__McCintLN_TArrayF;
extern G__linked_taginfo G__McCintLN_MGeomMirror;
extern G__linked_taginfo G__McCintLN_MGeomPMT;
extern G__linked_taginfo G__McCintLN_MMcConfigRunHeader;
extern G__linked_taginfo G__McCintLN_MGeomCorsikaCT;
extern G__linked_taginfo G__McCintLN_MMcCorsikaRunHeader;

/* STUB derived class for protected member access */
