/********************************************************************
* ImageCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ImageCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableImageCint();
extern void G__cpp_setup_inheritanceImageCint();
extern void G__cpp_setup_typetableImageCint();
extern void G__cpp_setup_memvarImageCint();
extern void G__cpp_setup_globalImageCint();
extern void G__cpp_setup_memfuncImageCint();
extern void G__cpp_setup_funcImageCint();
extern void G__set_cpp_environmentImageCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MImgCleanStd.h"
#include "MImgCleanTime.h"
#include "MImgCleanSimple.h"
#include "MHillas.h"
#include "MHillasSrc.h"
#include "MHillasExt.h"
#include "MHillasCalc.h"
#include "MImagePar.h"
#include "MNewImagePar.h"
#include "MNewImagePar2.h"
#include "MConcentration.h"
#include "MHHillas.h"
#include "MHHillasSrc.h"
#include "MHHillasExt.h"
#include "MHImagePar.h"
#include "MHNewImagePar.h"
#include "MHNewImagePar2.h"
#include "MHVsSize.h"
#include "MStereoPar.h"
#include "MStereoCalc.h"
#include "ImageIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ImageCintLN_TClass;
extern G__linked_taginfo G__ImageCintLN_TBuffer;
extern G__linked_taginfo G__ImageCintLN_TMemberInspector;
extern G__linked_taginfo G__ImageCintLN_TObject;
extern G__linked_taginfo G__ImageCintLN_TString;
extern G__linked_taginfo G__ImageCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ImageCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ImageCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ImageCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ImageCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ImageCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ImageCintLN_TEnv;
extern G__linked_taginfo G__ImageCintLN_MParContainer;
extern G__linked_taginfo G__ImageCintLN_MInputStreamID;
extern G__linked_taginfo G__ImageCintLN_MParList;
extern G__linked_taginfo G__ImageCintLN_MTask;
extern G__linked_taginfo G__ImageCintLN_MGGroupFrame;
extern G__linked_taginfo G__ImageCintLN_MGTask;
extern G__linked_taginfo G__ImageCintLN_MGeomCam;
extern G__linked_taginfo G__ImageCintLN_MGeom;
extern G__linked_taginfo G__ImageCintLN_MSignalCam;
extern G__linked_taginfo G__ImageCintLN_MPedPhotCam;
extern G__linked_taginfo G__ImageCintLN_MCameraData;
extern G__linked_taginfo G__ImageCintLN_MImgCleanStd;
extern G__linked_taginfo G__ImageCintLN_MImgCleanStdcLcLCleaningMethod_t;
extern G__linked_taginfo G__ImageCintLN_MSignalPix;
extern G__linked_taginfo G__ImageCintLN_Island;
extern G__linked_taginfo G__ImageCintLN_MImgCleanTime;
extern G__linked_taginfo G__ImageCintLN_vectorlEIslandcOallocatorlEIslandgRsPgR;
extern G__linked_taginfo G__ImageCintLN_reverse_iteratorlEvectorlEIslandcOallocatorlEIslandgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ImageCintLN_pairlEunsignedsPshortcOunsignedsPshortgR;
extern G__linked_taginfo G__ImageCintLN_listlEpairlEunsignedsPshortcOunsignedsPshortgRcOallocatorlEpairlEunsignedsPshortcOunsignedsPshortgRsPgRsPgR;
extern G__linked_taginfo G__ImageCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__ImageCintLN_reverse_iteratorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ImageCintLN_MImgCleanSimple;
extern G__linked_taginfo G__ImageCintLN_MImgCleanSimplecLcLCleaningMethod_t;
extern G__linked_taginfo G__ImageCintLN_TArrayF;
extern G__linked_taginfo G__ImageCintLN_TVector2;
extern G__linked_taginfo G__ImageCintLN_MHillas;
extern G__linked_taginfo G__ImageCintLN_MSrcPosCam;
extern G__linked_taginfo G__ImageCintLN_MHillasSrc;
extern G__linked_taginfo G__ImageCintLN_MHillasExt;
extern G__linked_taginfo G__ImageCintLN_TArrayL;
extern G__linked_taginfo G__ImageCintLN_MImagePar;
extern G__linked_taginfo G__ImageCintLN_MNewImagePar;
extern G__linked_taginfo G__ImageCintLN_MNewImagePar2;
extern G__linked_taginfo G__ImageCintLN_MConcentration;
extern G__linked_taginfo G__ImageCintLN_MHillasCalc;
extern G__linked_taginfo G__ImageCintLN_MHillasCalccLcLCalcCont_t;
extern G__linked_taginfo G__ImageCintLN_TH1;
extern G__linked_taginfo G__ImageCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ImageCintLN_TH1F;
extern G__linked_taginfo G__ImageCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ImageCintLN_TH2F;
extern G__linked_taginfo G__ImageCintLN_MH;
extern G__linked_taginfo G__ImageCintLN_MHHillas;
extern G__linked_taginfo G__ImageCintLN_MHHillasSrc;
extern G__linked_taginfo G__ImageCintLN_MHHillasExt;
extern G__linked_taginfo G__ImageCintLN_MHImagePar;
extern G__linked_taginfo G__ImageCintLN_MHNewImagePar;
extern G__linked_taginfo G__ImageCintLN_MHNewImagePar2;
extern G__linked_taginfo G__ImageCintLN_MHVsSize;
extern G__linked_taginfo G__ImageCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ImageCintLN_TVector3;
extern G__linked_taginfo G__ImageCintLN_MPointingPos;
extern G__linked_taginfo G__ImageCintLN_MStereoPar;
extern G__linked_taginfo G__ImageCintLN_MStereoCalc;

/* STUB derived class for protected member access */
