/********************************************************************
* PedestalCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PedestalCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePedestalCint();
extern void G__cpp_setup_inheritancePedestalCint();
extern void G__cpp_setup_typetablePedestalCint();
extern void G__cpp_setup_memvarPedestalCint();
extern void G__cpp_setup_globalPedestalCint();
extern void G__cpp_setup_memfuncPedestalCint();
extern void G__cpp_setup_funcPedestalCint();
extern void G__set_cpp_environmentPedestalCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MMcPedestalCopy.h"
#include "MMcPedestalNSBAdd.h"
#include "MExtractPedestal.h"
#include "MPedCalcPedRun.h"
#include "MPedCalcFromLoGain.h"
#include "MPedPhotCalc.h"
#include "MPedPhotCam.h"
#include "MPedPhotPix.h"
#include "MPedestalCam.h"
#include "MPedestalPix.h"
#include "MHPedestalCor.h"
#include "MPedestalSubtract.h"
#include "MPedestalSubtractedEvt.h"
#include "PedestalIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PedestalCintLN_TClass;
extern G__linked_taginfo G__PedestalCintLN_TBuffer;
extern G__linked_taginfo G__PedestalCintLN_TMemberInspector;
extern G__linked_taginfo G__PedestalCintLN_TObject;
extern G__linked_taginfo G__PedestalCintLN_TCollection;
extern G__linked_taginfo G__PedestalCintLN_TString;
extern G__linked_taginfo G__PedestalCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PedestalCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PedestalCintLN_TClonesArray;
extern G__linked_taginfo G__PedestalCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PedestalCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PedestalCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PedestalCintLN_TEnv;
extern G__linked_taginfo G__PedestalCintLN_MParContainer;
extern G__linked_taginfo G__PedestalCintLN_MInputStreamID;
extern G__linked_taginfo G__PedestalCintLN_MParList;
extern G__linked_taginfo G__PedestalCintLN_MTask;
extern G__linked_taginfo G__PedestalCintLN_MMcPedestalCopy;
extern G__linked_taginfo G__PedestalCintLN_MMcPedestalNSBAdd;
extern G__linked_taginfo G__PedestalCintLN_MArrayD;
extern G__linked_taginfo G__PedestalCintLN_MArrayI;
extern G__linked_taginfo G__PedestalCintLN_MGeomCam;
extern G__linked_taginfo G__PedestalCintLN_MExtractor;
extern G__linked_taginfo G__PedestalCintLN_MPedestalCam;
extern G__linked_taginfo G__PedestalCintLN_MRawEvtData;
extern G__linked_taginfo G__PedestalCintLN_MRawRunHeader;
extern G__linked_taginfo G__PedestalCintLN_MExtractTimeAndCharge;
extern G__linked_taginfo G__PedestalCintLN_MPedestalSubtractedEvt;
extern G__linked_taginfo G__PedestalCintLN_MRawEvtPixelIter;
extern G__linked_taginfo G__PedestalCintLN_MExtractPedestal;
extern G__linked_taginfo G__PedestalCintLN_MTriggerPattern;
extern G__linked_taginfo G__PedestalCintLN_MPedestalPix;
extern G__linked_taginfo G__PedestalCintLN_MPedCalcPedRun;
extern G__linked_taginfo G__PedestalCintLN_MPedCalcFromLoGain;
extern G__linked_taginfo G__PedestalCintLN_TArrayF;
extern G__linked_taginfo G__PedestalCintLN_MPedPhotCam;
extern G__linked_taginfo G__PedestalCintLN_MSignalCam;
extern G__linked_taginfo G__PedestalCintLN_MBadPixelsCam;
extern G__linked_taginfo G__PedestalCintLN_MPedPhotCalc;
extern G__linked_taginfo G__PedestalCintLN_MCamEvent;
extern G__linked_taginfo G__PedestalCintLN_MPedPhotPix;
extern G__linked_taginfo G__PedestalCintLN_TH2;
extern G__linked_taginfo G__PedestalCintLN_MArrayF;
extern G__linked_taginfo G__PedestalCintLN_TProfile;
extern G__linked_taginfo G__PedestalCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PedestalCintLN_MH;
extern G__linked_taginfo G__PedestalCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__PedestalCintLN_MHPedestalCor;
extern G__linked_taginfo G__PedestalCintLN_MPedestalSubtract;
extern G__linked_taginfo G__PedestalCintLN_MArrayS;

/* STUB derived class for protected member access */
