/********************************************************************
* AnalysisCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AnalysisCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAnalysisCint();
extern void G__cpp_setup_inheritanceAnalysisCint();
extern void G__cpp_setup_typetableAnalysisCint();
extern void G__cpp_setup_memvarAnalysisCint();
extern void G__cpp_setup_globalAnalysisCint();
extern void G__cpp_setup_memfuncAnalysisCint();
extern void G__cpp_setup_funcAnalysisCint();
extern void G__set_cpp_environmentAnalysisCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MGeomApply.h"
#include "MCameraData.h"
#include "MParameterCalc.h"
#include "MEnergyEstimate.h"
#include "MMatrixLoop.h"
#include "MMultiDimDistCalc.h"
#include "MEventRate.h"
#include "MEventRateCalc.h"
#include "MMcCalibrationUpdate.h"
#include "MSoftwareTrigger.h"
#include "MSoftwareTriggerCalc.h"
#include "AnalysisIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AnalysisCintLN_TClass;
extern G__linked_taginfo G__AnalysisCintLN_TBuffer;
extern G__linked_taginfo G__AnalysisCintLN_TMemberInspector;
extern G__linked_taginfo G__AnalysisCintLN_TObject;
extern G__linked_taginfo G__AnalysisCintLN_TString;
extern G__linked_taginfo G__AnalysisCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__AnalysisCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AnalysisCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisCintLN_TList;
extern G__linked_taginfo G__AnalysisCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AnalysisCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AnalysisCintLN_TEnv;
extern G__linked_taginfo G__AnalysisCintLN_TArrayD;
extern G__linked_taginfo G__AnalysisCintLN_MParContainer;
extern G__linked_taginfo G__AnalysisCintLN_MInputStreamID;
extern G__linked_taginfo G__AnalysisCintLN_MParList;
extern G__linked_taginfo G__AnalysisCintLN_MTask;
extern G__linked_taginfo G__AnalysisCintLN_MGeomCam;
extern G__linked_taginfo G__AnalysisCintLN_MGeomApply;
extern G__linked_taginfo G__AnalysisCintLN_TArrayC;
extern G__linked_taginfo G__AnalysisCintLN_MCamEvent;
extern G__linked_taginfo G__AnalysisCintLN_MSignalCam;
extern G__linked_taginfo G__AnalysisCintLN_MPedPhotCam;
extern G__linked_taginfo G__AnalysisCintLN_MCameraData;
extern G__linked_taginfo G__AnalysisCintLN_MData;
extern G__linked_taginfo G__AnalysisCintLN_MParameterD;
extern G__linked_taginfo G__AnalysisCintLN_MParameterCalc;
extern G__linked_taginfo G__AnalysisCintLN_MEnergyEstimate;
extern G__linked_taginfo G__AnalysisCintLN_MDirIter;
extern G__linked_taginfo G__AnalysisCintLN_MRead;
extern G__linked_taginfo G__AnalysisCintLN_MHMatrix;
extern G__linked_taginfo G__AnalysisCintLN_MMatrixLoop;
extern G__linked_taginfo G__AnalysisCintLN_MMatrixLoopcLcLOperationMode_t;
extern G__linked_taginfo G__AnalysisCintLN_MDataArray;
extern G__linked_taginfo G__AnalysisCintLN_MMultiDimDistCalc;
extern G__linked_taginfo G__AnalysisCintLN_MEventRate;
extern G__linked_taginfo G__AnalysisCintLN_MTime;
extern G__linked_taginfo G__AnalysisCintLN_MEventRateCalc;
extern G__linked_taginfo G__AnalysisCintLN_MExtractedSignalCam;
extern G__linked_taginfo G__AnalysisCintLN_MCalibrationChargeCam;
extern G__linked_taginfo G__AnalysisCintLN_MCalibrationQECam;
extern G__linked_taginfo G__AnalysisCintLN_MCalibrateData;
extern G__linked_taginfo G__AnalysisCintLN_MCalibrateDatacLcLSignalType_t;
extern G__linked_taginfo G__AnalysisCintLN_MMcFadcHeader;
extern G__linked_taginfo G__AnalysisCintLN_MMcCalibrationUpdate;
extern G__linked_taginfo G__AnalysisCintLN_MSoftwareTrigger;
extern G__linked_taginfo G__AnalysisCintLN_MRawEvtData;
extern G__linked_taginfo G__AnalysisCintLN_MPedestalSubtractedEvt;
extern G__linked_taginfo G__AnalysisCintLN_MSoftwareTriggerCalc;

/* STUB derived class for protected member access */
